In [1]:
import numpy as np
import pandas as pd
from queue import Queue
import datetime
from datetime import time

In [2]:
pd.set_option('display.max_columns', None)
# pd.set_option('display.max_rows', None)

In [3]:
df = pd.concat(pd.read_excel(r'C:\Users\Testing\PycharmProjects\multipage\data\F1F4.xlsx', sheet_name=None), ignore_index=True)

In [4]:
df = pd.read_excel(r'C:\Users\Testing\Downloads\NEW F1F4.xlsb', engine='pyxlsb')

In [ ]:
Venue--str,'NA'
Season--str,'NA'
Season Code--str,'NA'
Month--str,'NA'
Year--np.int64,int,0
Date--np.int64,int,0
NoR--np.int64,int,0
R No.--np.int64,int,0
F#--str,'NA'
RESULT--int,0
H. NO--int,0
Class--str,'NA'
Distance--str,'NA'
Age--str,'NA'
Wt--np.float64,float,0.0
Dr--int64,int,0
Sh--str,'NA'
LBW--np.float64,float,0.0

In [90]:
to_replace = [i for i in df2['LBW'].unique() if type(i) !=np.float64]
# to_replace
df2['Sh'].replace(to_replace,['NA']*len(to_replace),inplace=True)
df2['F#'].unique()

ValueError: Replacement lists must match in length. Expecting 3 got 0

In [52]:
[x for x in df2.columns]

['Sl',
 'Venue',
 'Season',
 'Season Code',
 'Month',
 'Year',
 'Date',
 'NoR',
 'R No.',
 'F#',
 'H. No',
 'RESULT',
 'Class',
 'Distance',
 'Race Time',
 'Age',
 'Wt',
 'Dr',
 'Sh',
 'LBW']

In [5]:
df.head(50)

,Sl,Venue,Season,Season Code,Month,Year,Date,NoR,R No.,F#,H. No,RESULT,Class,Distance,Race Time,Age,Wt,Dr,Sh,LBW
0,1,BLR,SUM,BS18,Aug,2018,180809,7,1,F1,1,2,V,1400M,0.604167,3y,54.5,1,A,0.00
1,2,BLR,SUM,BS18,Aug,2018,180809,7,1,F2,2,1,V,1400M,0.604167,3y,54.5,8,S,0.00
2,3,BLR,SUM,BS18,Aug,2018,180809,7,1,F3,3,0,V,1400M,0.604167,3y,54.5,11,A,10.25
3,4,BLR,SUM,BS18,Aug,2018,180809,7,1,F4,6,4,V,1400M,0.604167,3y,54.5,10,A,12.25
4,5,BLR,SUM,BS18,Aug,2018,180809,7,2,F2,1,1,IV,1600M,0.625,3y,56.0,6,S,0.00
5,6,BLR,SUM,BS18,Aug,2018,180809,7,2,F3,3,0,IV,1600M,0.625,3y,54.5,12,S,13.50
6,7,BLR,SUM,BS18,Aug,2018,180809,7,2,F4,6,0,IV,1600M,0.625,3y,56.0,3,S,19.25
7,8,BLR,SUM,BS18,Aug,2018,180809,7,2,F1,7,2,IV,1600M,0.625,3y,56.0,7,S,22.50
8,9,BLR,SUM,BS18,Aug,2018,180809,7,3,F2,1,1,III,1100M,0.645833,3y,56.0,9,S,0.00
9,10,BLR,SUM,BS18,Aug,2018,180809,7,3,F1,6,0,III,1100M,0.645833,3y,56.0,4,A,27.25
10,11,BLR,SUM,BS18,Aug,2018,180809,7,3,F3,7,0,III,1100M,0.645833,3y,54.5,2,S,30.00
11,12,BLR,SUM,BS18,Aug,2018,180809,7,3,F4,9,2,III,1100M,0.645833,3y,54.5,5,S,30.00
12,13,BLR,SUM,BS18,Aug,2018,180809,7,4,F1,1,0,II,1200M,0.666667,3y,54.5,7,A,0.00
13,14,BLR,SUM,BS18,Aug,2018,180809,7,4,F4,2,0,II,1200M,0.666667,3y,56.0,9,A,1.50
14,15,BLR,SUM,BS18,Aug,2018,180809,7,4,F3,5,0,II,1200M,0.666667,3y,56.0,8,A,10.00
15,16,BLR,SUM,BS18,Aug,2018,180809,7,4,F2,6,2,II,1200M,0.666667,3y,56.0,4,S,11.00
16,17,BLR,SUM,BS18,Aug,2018,180809,7,5,F2,3,4,III,1400M,0.6875,3y,54.5,3,A,11.00
17,18,BLR,SUM,BS18,Aug,2018,180809,7,5,F1,6,1,III,1400M,0.6875,3y,54.5,12,A,0.00
18,19,BLR,SUM,BS18,Aug,2018,180809,7,5,F3,7,2,III,1400M,0.6875,3y,54.5,6,S,17.50
19,20,BLR,SUM,BS18,Aug,2018,180809,7,5,F4,8,0,III,1400M,0.6875,3y,56.0,11,A,17.50
20,21,BLR,SUM,BS18,Aug,2018,180809,7,6,F1,2,0,III,1100M,0.708333,3y,56.0,5,A,19.50
21,22,BLR,SUM,BS18,Aug,2018,180809,7,6,F2,4,2,III,1100M,0.708333,3y,54.5,10,A,22.25
22,23,BLR,SUM,BS18,Aug,2018,180809,7,6,F3,5,3,III,1100M,0.708333,3y,54.5,1,A,26.75
23,24,BLR,SUM,BS18,Aug,2018,180809,7,6,F4,8,0,III,1100M,0.708333,3y,54.5,2,S,32.25
24,25,BLR,SUM,BS18,Aug,2018,180809,7,7,F2,2,0,IV,1200M,0.729167,5y,56.5,11,S,0.00
25,26,BLR,SUM,BS18,Aug,2018,180809,7,7,F4,6,3,IV,1200M,0.729167,4y,55.5,3,S,3.50
26,27,BLR,SUM,BS18,Aug,2018,180809,7,7,F1,8,0,IV,1200M,0.729167,6y,60.5,1,S,4.00
27,28,BLR,SUM,BS18,Aug,2018,180809,7,7,F3,10,2,IV,1200M,0.729167,4y,61.5,2,A,4.75
28,29,BLR,SUM,BS18,Aug,2018,180810,7,1,F1,6,0,V,1200M,0.604167,4y,58.5,10,S,6.75
29,30,BLR,SUM,BS18,Aug,2018,180810,7,1,F3,7,1,V,1200M,0.604167,5y,50.0,9,S,0.00
30,31,BLR,SUM,BS18,Aug,2018,180810,7,1,F2,8,3,V,1200M,0.604167,4y,62.5,7,S,13.75
31,32,BLR,SUM,BS18,Aug,2018,180810,7,1,F4,5,0,V,1200M,0.604167,5y,56.0,6,S,14.50
32,33,BLR,SUM,BS18,Aug,2018,180810,7,2,F2,1,2,M3y,1100M,0.625,4y,56.5,4,S,14.50
33,34,BLR,SUM,BS18,Aug,2018,180810,7,2,F3,7,3,M3y,1100M,0.625,4y,57.5,5,S,18.50
34,35,BLR,SUM,BS18,Aug,2018,180810,7,2,F1,8,1,M3y,1100M,0.625,4y,60.0,8,S,0.00
35,36,BLR,SUM,BS18,Aug,2018,180810,7,2,F4,2,0,M3y,1100M,0.625,4y,52.5,12,S,28.00
36,37,BLR,SUM,BS18,Aug,2018,180810,7,3,F2,4,3,III,1600M,0.645833,3y,61.0,9,S,0.00
37,38,BLR,SUM,BS18,Aug,2018,180810,7,3,F3,5,2,III,1600M,0.645833,4y,62.0,7,A,1.75
38,39,BLR,SUM,BS18,Aug,2018,180810,7,3,F1,6,1,III,1600M,0.645833,4y,57.0,3,S,0.00
39,40,BLR,SUM,BS18,Aug,2018,180810,7,3,F4,2,0,III,1600M,0.645833,4y,52.0,2,S,7.25
40,41,BLR,SUM,BS18,Aug,2018,180810,7,4,F3,2,4,I,1400M,0.666667,3y,51.0,4,S,8.75
41,42,BLR,SUM,BS18,Aug,2018,180810,7,4,F2,3,2,I,1400M,0.666667,6y,57.0,5,S,9.25
42,43,BLR,SUM,BS18,Aug,2018,180810,7,4,F1,9,1,I,1400M,0.666667,3y,62.5,10,A,0.00
43,44,BLR,SUM,BS18,Aug,2018,180810,7,4,F4,4,0,I,1400M,0.666667,3y,62.5,8,A,13.75
44,45,BLR,SUM,BS18,Aug,2018,180810,7,5,F1,2,0,V,1600M,0.6875,3y,58.5,11,A,13.75
45,46,BLR,SUM,BS18,Aug,2018,180810,7,5,F2,3,0,V,1600M,0.6875,3y,51.5,6,S,16.00
46,47,BLR,SUM,BS18,Aug,2018,180810,7,5,F3,4,3,V,1600M,0.6875,5y,51.5,1,S,17.00
47,48,BLR,SUM,BS18,Aug,2018,180810,7,5,F4,5,0,V,1600M,0.6875,3y,55.5,6,A,0.00
48,49,BLR,SUM,BS18,Aug,2018,180810,7,6,F2,1,1,M3y,1400M,0.708333,4y,54.5,2,A,0.00
49,50,BLR,SUM,BS18,Aug,2018,180810,7,6,F3,4,0,M3y,1400M,0.708333,3y,54.0,5,A,5.25

In [16]:
# df['R No.'].replace([np.nan], [0], inplace=True)
# df['NoR'].unique()
df['Race Time'].unique()
a = [x for x in df['Race Time'].unique() if type(x)==str]
anew = [datetime.time(int(x.split('.')[0]),int(x.split('.')[1])) for x in a]
anew

[datetime.time(2, 30),
 datetime.time(3, 0),
 datetime.time(3, 30),
 datetime.time(4, 0),
 datetime.time(4, 30),
 datetime.time(5, 0),
 datetime.time(5, 30)]

In [18]:
df['Race Time'].replace(a, anew, inplace=True)
df['Race Time'].replace([np.nan],[datetime.time(0,0)], inplace=True)
df['Race Time'].unique()

array([datetime.time(14, 30), datetime.time(15, 0), datetime.time(15, 30),
       datetime.time(16, 0), datetime.time(16, 30), datetime.time(17, 0),
       datetime.time(17, 30), datetime.time(14, 45),
       datetime.time(15, 15), datetime.time(15, 45),
       datetime.time(16, 15), datetime.time(16, 45),
       datetime.time(17, 15), datetime.time(14, 15),
       datetime.time(13, 45), datetime.time(14, 20),
       datetime.time(14, 55), datetime.time(16, 5), datetime.time(16, 40),
       datetime.time(13, 15), datetime.time(15, 20),
       datetime.time(15, 55), datetime.time(17, 10),
       datetime.time(17, 50), datetime.time(17, 45),
       datetime.time(13, 30), datetime.time(14, 0), datetime.time(2, 30),
       datetime.time(3, 0), datetime.time(3, 30), datetime.time(4, 0),
       datetime.time(4, 30), datetime.time(5, 0), datetime.time(5, 30),
       datetime.time(15, 10), datetime.time(16, 20),
       datetime.time(16, 55), datetime.time(14, 35), datetime.time(15, 5),
       datetime.time(15, 40), datetime.time(16, 50),
       datetime.time(17, 25), datetime.time(0, 0), datetime.time(13, 0),
       datetime.time(12, 45)], dtype=object)

In [24]:
df['Race Time'] = [x.strftime("%H:%M:%S") for x in df['Race Time']]
df['Race Time'].unique()

array(['14:30:00', '15:00:00', '15:30:00', '16:00:00', '16:30:00',
       '17:00:00', '17:30:00', '14:45:00', '15:15:00', '15:45:00',
       '16:15:00', '16:45:00', '17:15:00', '14:15:00', '13:45:00',
       '14:20:00', '14:55:00', '16:05:00', '16:40:00', '13:15:00',
       '15:20:00', '15:55:00', '17:10:00', '17:50:00', '17:45:00',
       '13:30:00', '14:00:00', '02:30:00', '03:00:00', '03:30:00',
       '04:00:00', '04:30:00', '05:00:00', '05:30:00', '15:10:00',
       '16:20:00', '16:55:00', '14:35:00', '15:05:00', '15:40:00',
       '16:50:00', '17:25:00', '00:00:00', '13:00:00', '12:45:00'],
      dtype=object)

In [6]:
for i in ['Venue', 'Season', 'Season Code', 'Month', 'F#', 'Class', 'Distance', 'Age', 'Sh']:
    try:
        to_replace = [i for i in df[i].unique() if type(i) != str]
        df[i].replace(to_replace,['NA']*len(to_replace),inplace=True)
    except:
        pass

for i in ['Year', 'Date', 'NoR', 'R No.', 'RESULT', 'H. No', 'Dr']:
    try:
        to_replace = [i for i in df[i].unique() if type(i) != int and type(i) != np.int64]
        df[i].replace(to_replace,[0]*len(to_replace),inplace=True)
    except:
        pass

for i in ['Wt', 'LBW']:
    try:
        to_replace = [i for i in df[i].unique() if type(i) != float and type(i) != np.float64]
        df[i].replace(to_replace,[0.0]*len(to_replace),inplace=True)
    except:
        pass

In [7]:
df.rename(columns = {'F#':'F'}, inplace = True)
df['fav_num']=df.apply(lambda row:int(row.F.strip('F')), axis=1)
# df.RESULT.replace(['NR','Rain','q'],[np.nan,np.nan,0], inplace=True)
df.dropna(subset=['RESULT'], inplace=True)
df['RESULT']=df['RESULT'].astype('int64')
df['Truth']=df['fav_num']==df['RESULT']
df['f_r'] = list(zip(df.fav_num, df.RESULT))
# df.Class.replace(np.nan, "-", inplace=True)
df.Distance.replace(["1400 M", "1600 M", "1100 M", "1200 M", np.nan], ["1400M", "1600M", "1100M", "1200M", "-"], inplace=True)

In [8]:
df

,Sl,Venue,Season,Season Code,Month,Year,Date,NoR,R No.,F,H. No,RESULT,Class,Distance,Race Time,Age,Wt,Dr,Sh,LBW,fav_num,Truth,f_r
0,1,BLR,SUM,BS18,Aug,2018,180809,7,1,F1,1,2,V,1400M,0.604167,3y,54.5,1,A,0.00,1,False,"(1, 2)"
1,2,BLR,SUM,BS18,Aug,2018,180809,7,1,F2,2,1,V,1400M,0.604167,3y,54.5,8,S,0.00,2,False,"(2, 1)"
2,3,BLR,SUM,BS18,Aug,2018,180809,7,1,F3,3,0,V,1400M,0.604167,3y,54.5,11,A,10.25,3,False,"(3, 0)"
3,4,BLR,SUM,BS18,Aug,2018,180809,7,1,F4,6,4,V,1400M,0.604167,3y,54.5,10,A,12.25,4,True,"(4, 4)"
4,5,BLR,SUM,BS18,Aug,2018,180809,7,2,F2,1,1,IV,1600M,0.625,3y,56.0,6,S,0.00,2,False,"(2, 1)"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21591,21592,HKJC-ST,21M,C+3 Course,SEP,2021,210926,10,9,F4,10,6,III,1400M,0.715278,3y,54.5,3,A,3.00,4,False,"(4, 6)"
21592,21593,HKJC-ST,21M,C+3 Course,SEP,2021,210926,10,10,F1,5,7,II,1200M,0.739583,3y,54.5,8,A,5.25,1,False,"(1, 7)"
21593,21594,HKJC-ST,21M,C+3 Course,SEP,2021,210926,10,10,F2,1,2,II,1200M,0.739583,3y,56.0,2,A,6.50,2,True,"(2, 2)"
21594,21595,HKJC-ST,21M,C+3 Course,SEP,2021,210926,10,10,F3,2,12,II,1200M,0.739583,3y,56.0,6,A,11.75,3,False,"(3, 12)"
21595,21596,HKJC-ST,21M,C+3 Course,SEP,2021,210926,10,10,F4,0,0,II,1200M,0.739583,3y,54.5,12,S,11.75,4,False,"(4, 0)"

In [7]:
blrdf=df[df['Venue']=='BLR']

In [9]:
combo=[(1, 0),(1, 1),(1, 2),(1, 3),(1, 4),(2, 0),(2, 1),(2, 2),(2, 3),(2, 4),(3, 0),(3, 1),(3, 2),(3, 3),(3, 4),(4, 0),(4, 1),(4, 2),(4, 3),(4, 4)]
race_stats = df.groupby(["Venue","Season Code","Date","Month","Year", "R No.", "Distance", "Class", "f_r"], as_index=True).size().unstack(fill_value=0)
mis_col = [i for i in combo if i not in race_stats.columns]
for col in mis_col:
    race_stats[col] = [0] * len(race_stats)
race_stats = race_stats[combo]

race_stats

f_r                                                        (1, 0)  (1, 1)  \
Venue Season Code Date   Month Year R No. Distance Class
BLR   BS18        180809 Aug   2018 1     1400M    V            0       0
                                    2     1600M    IV           0       0
                                    3     1100M    III          1       0
                                    4     1200M    II           1       0
                                    5     1400M    III          0       1
...                                                           ...     ...
PUN   PR19        191026 OCT   2019 4     1400M    M3y          0       0
                                    5     2000M    T-4y&o       1       0
                                    6     1600M    IV           0       1
                                    7     1200M    IV           0       1
                                    8     1000M    V 5y&o       1       0

f_r                                                        (1, 2)  (1, 3)  \
Venue Season Code Date   Month Year R No. Distance Class
BLR   BS18        180809 Aug   2018 1     1400M    V            1       0
                                    2     1600M    IV           1       0
                                    3     1100M    III          0       0
                                    4     1200M    II           0       0
                                    5     1400M    III          0       0
...                                                           ...     ...
PUN   PR19        191026 OCT   2019 4     1400M    M3y          1       0
                                    5     2000M    T-4y&o       0       0
                                    6     1600M    IV           0       0
                                    7     1200M    IV           0       0
                                    8     1000M    V 5y&o       0       0

f_r                                                        (1, 4)  (2, 0)  \
Venue Season Code Date   Month Year R No. Distance Class
BLR   BS18        180809 Aug   2018 1     1400M    V            0       0
                                    2     1600M    IV           0       0
                                    3     1100M    III          0       0
                                    4     1200M    II           0       0
                                    5     1400M    III          0       0
...                                                           ...     ...
PUN   PR19        191026 OCT   2019 4     1400M    M3y          0       0
                                    5     2000M    T-4y&o       0       1
                                    6     1600M    IV           0       1
                                    7     1200M    IV           0       1
                                    8     1000M    V 5y&o       0       1

f_r                                                        (2, 1)  (2, 2)  \
Venue Season Code Date   Month Year R No. Distance Class
BLR   BS18        180809 Aug   2018 1     1400M    V            1       0
                                    2     1600M    IV           1       0
                                    3     1100M    III          1       0
                                    4     1200M    II           0       1
                                    5     1400M    III          0       0
...                                                           ...     ...
PUN   PR19        191026 OCT   2019 4     1400M    M3y          0       0
                                    5     2000M    T-4y&o       0       0
                                    6     1600M    IV           0       0
                                    7     1200M    IV           0       0
                                    8     1000M    V 5y&o       0       0

f_r                                                        (2, 3)  (2, 4)  \
Venue Season Code Date   Month Year R No. Distance Class
BLR   BS18        180809 Aug   2018 1     1400M    V            0       0
                                    2     1600M    IV           0       0
                                    3     1100M    III          0       0
                                    4     1200M    II           0       0
                                    5     1400M    III          0       1
...                                                           ...     ...
PUN   PR19        191026 OCT   2019 4     1400M    M3y          1       0
                                    5     2000M    T-4y&o       0       0
                                    6     1600M    IV           0       0
                                    7     1200M    IV           0       0
                                    8     1000M    V 5y&o       0       0

f_r                                                        (3, 0)  (3, 1)  \
Venue Season Code Date   Month Year R No. Distance Class
BLR   BS18        180809 Aug   2018 1     1400M    V            1       0
                                    2     1600M    IV           1       0
                                    3     1100M    III          1       0
                                    4     1200M    II           1       0
                                    5     1400M    III          0       0
...                                                           ...     ...
PUN   PR19        191026 OCT   2019 4     1400M    M3y          1       0
                                    5     2000M    T-4y&o       0       0
                                    6     1600M    IV           0       0
                                    7     1200M    IV           0       0
                                    8     1000M    V 5y&o       1       0

f_r                                                        (3, 2)  (3, 3)  \
Venue Season Code Date   Month Year R No. Distance Class
BLR   BS18        180809 Aug   2018 1     1400M    V            0       0
                                    2     1600M    IV           0       0
                                    3     1100M    III          0       0
                                    4     1200M    II           0       0
                                    5     1400M    III          1       0
...                                                           ...     ...
PUN   PR19        191026 OCT   2019 4     1400M    M3y          0       0
                                    5     2000M    T-4y&o       1       0
                                    6     1600M    IV           0       1
                                    7     1200M    IV           0       1
                                    8     1000M    V 5y&o       0       0

f_r                                                        (3, 4)  (4, 0)  \
Venue Season Code Date   Month Year R No. Distance Class
BLR   BS18        180809 Aug   2018 1     1400M    V            0       0
                                    2     1600M    IV           0       1
                                    3     1100M    III          0       0
                                    4     1200M    II           0       1
                                    5     1400M    III          0       1
...                                                           ...     ...
PUN   PR19        191026 OCT   2019 4     1400M    M3y          0       0
                                    5     2000M    T-4y&o       0       1
                                    6     1600M    IV           0       1
                                    7     1200M    IV           0       1
                                    8     1000M    V 5y&o       0       0

f_r                                                        (4, 1)  (4, 2)  \
Venue Season Code Date   Month Year R No. Distance Class
BLR   BS18        180809 Aug   2018 1     1400M    V            0       0
                                    2     1600M    IV           0       0
                                    3     1100M    III          0       1
                                    4     1200M    II           0       0
                                    5     1400M    III          0       0
...                                                           ...     ...
PUN   PR19        191026 OCT   2019 4     1400M    M3y          1       0
                                    5     2000M    T-4y&o       0       0
                                    6     1600M    IV           0       0
                                    7     1200M    IV           0       0
                                    8     1000M    V 5y&o       0       0

f_r                                                        (4, 3)  (4, 4)
Venue Season Code Date   Month Year R No. Distance Class
BLR   BS18        180809 Aug   2018 1     1400M    V            0       1
                                    2     1600M    IV           0       0
                                    3     1100M    III          0       0
                                    4     1200M    II           0       0
                                    5     1400M    III          0       0
...                                                           ...     ...
PUN   PR19        191026 OCT   2019 4     1400M    M3y          0       0
                                    5     2000M    T-4y&o       0       0
                                    6     1600M    IV           0       0
                                    7     1200M    IV           0       0
                                    8     1000M    V 5y&o       1       0

[5483 rows x 20 columns]

In [10]:
len(race_stats)

5483

In [11]:
race_stats['F12'] = race_stats[(1,1)]*race_stats[(2,2)]
race_stats['F13'] = race_stats[(1,1)]*race_stats[(3,2)]
race_stats['F14'] = race_stats[(1,1)]*race_stats[(4,2)]

race_stats['F21'] = race_stats[(2,1)]*race_stats[(1,2)]
race_stats['F23'] = race_stats[(2,1)]*race_stats[(3,2)]
race_stats['F24'] = race_stats[(2,1)]*race_stats[(4,2)]

race_stats['F31'] = race_stats[(3,1)]*race_stats[(1,2)]
race_stats['F32'] = race_stats[(3,1)]*race_stats[(2,2)]
race_stats['F34'] = race_stats[(3,1)]*race_stats[(4,2)]

race_stats['F41'] = race_stats[(4,1)]*race_stats[(1,2)]
race_stats['F42'] = race_stats[(4,1)]*race_stats[(2,2)]
race_stats['F43'] = race_stats[(4,1)]*race_stats[(3,2)]

In [12]:
race_stats['F12|F21'] = (race_stats[(1,1)]*race_stats[(2,2)]) | (race_stats[(1,2)]*race_stats[(2,1)])
race_stats['F13|F31'] = (race_stats[(1,1)]*race_stats[(3,2)]) | (race_stats[(1,2)]*race_stats[(3,1)])
race_stats['F14|F41'] = (race_stats[(1,1)]*race_stats[(4,2)]) | (race_stats[(1,2)]*race_stats[(4,1)])

# race_stats['F21'] = race_stats[(2,1)]*race_stats[(1,2)]
race_stats['F23|F32'] = (race_stats[(2,1)]*race_stats[(3,2)]) | (race_stats[(2,2)]*race_stats[(3,1)])
race_stats['F24|F42'] = (race_stats[(2,1)]*race_stats[(4,2)]) | (race_stats[(2,2)]*race_stats[(4,1)])

# race_stats['F31'] = race_stats[(3,1)]*race_stats[(1,2)]
# race_stats['F32'] = race_stats[(3,1)]*race_stats[(2,2)]
race_stats['F34|F43'] = (race_stats[(3,1)]*race_stats[(4,2)]) | (race_stats[(3,2)]*race_stats[(4,1)])

# race_stats['F41'] = race_stats[(4,1)]*race_stats[(1,2)]
# race_stats['F42'] = race_stats[(4,1)]*race_stats[(2,2)]
# race_stats['F43'] = race_stats[(4,1)]*race_stats[(3,2)]

In [13]:
race_stats['F1|F2'] = race_stats[(1,1)] | race_stats[(2,1)]
race_stats['F1|F3'] = race_stats[(1,1)] | race_stats[(3,1)]
race_stats['F1|F4'] = race_stats[(1,1)] | race_stats[(4,1)]

race_stats['F2|F3'] = race_stats[(2,1)] | race_stats[(3,1)]
race_stats['F2|F4'] = race_stats[(2,1)] | race_stats[(4,1)]

race_stats['F3|F4'] = race_stats[(3,1)] | race_stats[(4,1)]

race_stats['F1|F2|F3'] = race_stats[(1,1)] | race_stats[(2,1)] | race_stats[(3,1)]
race_stats['F1|F2|F4'] = race_stats[(1,1)] | race_stats[(2,1)] | race_stats[(4,1)]
race_stats['F1|F3|F4'] = race_stats[(1,1)] | race_stats[(3,1)] | race_stats[(4,1)]
race_stats['F2|F3|F4'] = race_stats[(2,1)] | race_stats[(3,1)] | race_stats[(4,1)]

race_stats['F1|F2|F3|F4'] = race_stats[(1,1)] | race_stats[(2,1)] | race_stats[(3,1)] | race_stats[(4,1)]

In [14]:
race_stats['F123'] = race_stats[(1,1)]*race_stats[(2,2)]*race_stats[(3,3)]
race_stats['F124'] = race_stats[(1,1)]*race_stats[(2,2)]*race_stats[(4,3)]
race_stats['F132'] = race_stats[(1,1)]*race_stats[(3,2)]*race_stats[(2,3)]
race_stats['F134'] = race_stats[(1,1)]*race_stats[(3,2)]*race_stats[(4,3)]
race_stats['F142'] = race_stats[(1,1)]*race_stats[(4,2)]*race_stats[(2,3)]
race_stats['F143'] = race_stats[(1,1)]*race_stats[(4,2)]*race_stats[(3,3)]

race_stats['F213'] = race_stats[(2,1)]*race_stats[(1,2)]*race_stats[(3,3)]
race_stats['F214'] = race_stats[(2,1)]*race_stats[(1,2)]*race_stats[(4,3)]
race_stats['F231'] = race_stats[(2,1)]*race_stats[(3,2)]*race_stats[(1,3)]
race_stats['F234'] = race_stats[(2,1)]*race_stats[(3,2)]*race_stats[(4,3)]
race_stats['F241'] = race_stats[(2,1)]*race_stats[(4,2)]*race_stats[(1,3)]
race_stats['F243'] = race_stats[(2,1)]*race_stats[(4,2)]*race_stats[(3,3)]

race_stats['F312'] = race_stats[(3,1)]*race_stats[(1,2)]*race_stats[(2,3)]
race_stats['F314'] = race_stats[(3,1)]*race_stats[(1,2)]*race_stats[(4,3)]
race_stats['F321'] = race_stats[(3,1)]*race_stats[(2,2)]*race_stats[(1,3)]
race_stats['F324'] = race_stats[(3,1)]*race_stats[(2,2)]*race_stats[(4,3)]
race_stats['F341'] = race_stats[(3,1)]*race_stats[(4,2)]*race_stats[(1,3)]
race_stats['F342'] = race_stats[(3,1)]*race_stats[(4,2)]*race_stats[(2,3)]

race_stats['F412'] = race_stats[(4,1)]*race_stats[(1,2)]*race_stats[(2,3)]
race_stats['F413'] = race_stats[(4,1)]*race_stats[(1,2)]*race_stats[(3,3)]
race_stats['F421'] = race_stats[(4,1)]*race_stats[(2,2)]*race_stats[(1,3)]
race_stats['F423'] = race_stats[(4,1)]*race_stats[(2,2)]*race_stats[(3,3)]
race_stats['F431'] = race_stats[(4,1)]*race_stats[(3,2)]*race_stats[(1,3)]
race_stats['F432'] = race_stats[(4,1)]*race_stats[(3,2)]*race_stats[(2,3)]

In [15]:
race_stats['F1234'] = race_stats[(1,1)]*race_stats[(2,2)]*race_stats[(3,3)]*race_stats[(4,4)]
race_stats['F1243'] = race_stats[(1,1)]*race_stats[(2,2)]*race_stats[(4,3)]*race_stats[(3,4)]
race_stats['F1324'] = race_stats[(1,1)]*race_stats[(3,2)]*race_stats[(2,3)]*race_stats[(4,4)]
race_stats['F1342'] = race_stats[(1,1)]*race_stats[(3,2)]*race_stats[(4,3)]*race_stats[(2,4)]
race_stats['F1423'] = race_stats[(1,1)]*race_stats[(4,2)]*race_stats[(2,3)]*race_stats[(3,4)]
race_stats['F1432'] = race_stats[(1,1)]*race_stats[(4,2)]*race_stats[(3,3)]*race_stats[(2,4)]

race_stats['F2134'] = race_stats[(2,1)]*race_stats[(1,2)]*race_stats[(3,3)]*race_stats[(4,4)]
race_stats['F2143'] = race_stats[(2,1)]*race_stats[(1,2)]*race_stats[(4,3)]*race_stats[(3,4)]
race_stats['F2314'] = race_stats[(2,1)]*race_stats[(3,2)]*race_stats[(1,3)]*race_stats[(4,4)]
race_stats['F2341'] = race_stats[(2,1)]*race_stats[(3,2)]*race_stats[(4,3)]*race_stats[(1,4)]
race_stats['F2413'] = race_stats[(2,1)]*race_stats[(4,2)]*race_stats[(1,3)]*race_stats[(3,4)]
race_stats['F2431'] = race_stats[(2,1)]*race_stats[(4,2)]*race_stats[(3,3)]*race_stats[(1,4)]

race_stats['F3124'] = race_stats[(3,1)]*race_stats[(1,2)]*race_stats[(2,3)]*race_stats[(4,4)]
race_stats['F3142'] = race_stats[(3,1)]*race_stats[(1,2)]*race_stats[(4,3)]*race_stats[(2,4)]
race_stats['F3214'] = race_stats[(3,1)]*race_stats[(2,2)]*race_stats[(1,3)]*race_stats[(4,4)]
race_stats['F3241'] = race_stats[(3,1)]*race_stats[(2,2)]*race_stats[(4,3)]*race_stats[(1,4)]
race_stats['F3412'] = race_stats[(3,1)]*race_stats[(4,2)]*race_stats[(1,3)]*race_stats[(2,4)]
race_stats['F3421'] = race_stats[(3,1)]*race_stats[(4,2)]*race_stats[(2,3)]*race_stats[(1,4)]

race_stats['F4123'] = race_stats[(4,1)]*race_stats[(1,2)]*race_stats[(2,3)]*race_stats[(3,4)]
race_stats['F4132'] = race_stats[(4,1)]*race_stats[(1,2)]*race_stats[(3,3)]*race_stats[(2,4)]
race_stats['F4213'] = race_stats[(4,1)]*race_stats[(2,2)]*race_stats[(1,3)]*race_stats[(3,4)]
race_stats['F4231'] = race_stats[(4,1)]*race_stats[(2,2)]*race_stats[(3,3)]*race_stats[(1,4)]
race_stats['F4312'] = race_stats[(4,1)]*race_stats[(3,2)]*race_stats[(1,3)]*race_stats[(2,4)]
race_stats['F4321'] = race_stats[(4,1)]*race_stats[(3,2)]*race_stats[(2,3)]*race_stats[(1,4)]

In [16]:
race_stats.head(50)

f_r                                                        (1, 0)  (1, 1)  \
Venue Season Code Date   Month Year R No. Distance Class
BLR   BS18        180809 Aug   2018 1     1400M    V            0       0
                                    2     1600M    IV           0       0
                                    3     1100M    III          1       0
                                    4     1200M    II           1       0
                                    5     1400M    III          0       1
                                    6     1100M    III          1       0
                                    7     1200M    IV           1       0
                  180810 Aug   2018 1     1200M    V            1       0
                                    2     1100M    M3y          0       1
                                    3     1600M    III          0       1
                                    4     1400M    I            0       1
                                    5     1600M    V            1       0
                                    6     1400M    M3y          0       0
                                    7     1200M    IV           0       0
      BS19        190518 May   2018 1     1200M    M3y          1       0
                                    2     1600M    V            0       1
                                    3     1400M    III          0       1
                                    4     1200M    I            0       0
                                    5     1200M    M3y          0       0
                                    6     1400M    IV           1       0
                                    7     1100M    IV           1       0
                  190519 May   2018 1     1100M    M3y          0       0
                                    2     1200M    V            0       1
                                    3     1400M    II           0       0
                                    4     1400M    T 3y         0       1
                                    5     1200M    III          0       1
                                    6     1400M    I            0       1
                                    7     1200M    IV           0       1
                  190525 May   2019 1     1100M    V            0       1
                                    2     1400M    M3y          0       0
                                    3     1100M    V            0       0
                                    4     1600M    I            0       0
                                    5     1400M    III          0       0
                                    6     1200M    IV           1       0
                                    7     1400M    IV           0       1
                  190526 May   2019 1     1400M    V            0       0
                                    2     1600M    IV           0       0
                                    3     1200M    III          1       0
                                    4     1400M    T 4y&o       1       0
                                    5     1200M    II           0       1
                                    6     1400M    IV           0       1
                                    7     1200M    M3y          0       0
                  190601 Jun   2019 1     1200M    IV           0       1
                                    2     1200M    IV           0       0
                                    3     1200M    M3y          0       1
                                    4     1200M    II           0       1
                                    5     1400M    I            0       1
                                    6     1200M    M3y          0       1
                  190602 Jun   2019 1     1600M    M3y          0       1
                                    2     1100M    V            0       0

f_r                                                        (1, 2)  (1, 3)  \
Venue Season Code Date   Month Year R No. Distance Class
BLR   BS18        180809 Aug   2018 1     1400M    V            1       0
                                    2     1600M    IV           1       0
                                    3     1100M    III          0       0
                                    4     1200M    II           0       0
                                    5     1400M    III          0       0
                                    6     1100M    III          0       0
                                    7     1200M    IV           0       0
                  180810 Aug   2018 1     1200M    V            0       0
                                    2     1100M    M3y          0       0
                                    3     1600M    III          0       0
                                    4     1400M    I            0       0
                                    5     1600M    V            0       0
                                    6     1400M    M3y          1       0
                                    7     1200M    IV           1       0
      BS19        190518 May   2018 1     1200M    M3y          0       0
                                    2     1600M    V            0       0
                                    3     1400M    III          0       0
                                    4     1200M    I            1       0
                                    5     1200M    M3y          0       0
                                    6     1400M    IV           0       0
                                    7     1100M    IV           0       0
                  190519 May   2018 1     1100M    M3y          0       1
                                    2     1200M    V            0       0
                                    3     1400M    II           1       0
                                    4     1400M    T 3y         0       0
                                    5     1200M    III          0       0
                                    6     1400M    I            0       0
                                    7     1200M    IV           0       0
                  190525 May   2019 1     1100M    V            0       0
                                    2     1400M    M3y          0       1
                                    3     1100M    V            1       0
                                    4     1600M    I            1       0
                                    5     1400M    III          1       0
                                    6     1200M    IV           0       0
                                    7     1400M    IV           0       0
                  190526 May   2019 1     1400M    V            0       1
                                    2     1600M    IV           1       0
                                    3     1200M    III          0       0
                                    4     1400M    T 4y&o       0       0
                                    5     1200M    II           0       0
                                    6     1400M    IV           0       0
                                    7     1200M    M3y          1       0
                  190601 Jun   2019 1     1200M    IV           0       0
                                    2     1200M    IV           1       0
                                    3     1200M    M3y          0       0
                                    4     1200M    II           0       0
                                    5     1400M    I            0       0
                                    6     1200M    M3y          0       0
                  190602 Jun   2019 1     1600M    M3y          0       0
                                    2     1100M    V            1       0

f_r                                                        (1, 4)  (2, 0)  \
Venue Season Code Date   Month Year R No. Distance Class
BLR   BS18        180809 Aug   2018 1     1400M    V            0       0
                                    2     1600M    IV           0       0
                                    3     1100M    III          0       0
                                    4     1200M    II           0       0
                                    5     1400M    III          0       0
                                    6     1100M    III          0       0
                                    7     1200M    IV           0       1
                  180810 Aug   2018 1     1200M    V            0       0
                                    2     1100M    M3y          0       0
                                    3     1600M    III          0       0
                                    4     1400M    I            0       0
                                    5     1600M    V            0       1
                                    6     1400M    M3y          0       0
                                    7     1200M    IV           0       0
      BS19        190518 May   2018 1     1200M    M3y          0       0
                                    2     1600M    V            0       0
                                    3     1400M    III          0       0
                                    4     1200M    I            0       1
                                    5     1200M    M3y          1       0
                                    6     1400M    IV           0       0
                                    7     1100M    IV           0       1
                  190519 May   2018 1     1100M    M3y          0       0
                                    2     1200M    V            0       0
                                    3     1400M    II           0       0
                                    4     1400M    T 3y         0       0
                                    5     1200M    III          0       0
                                    6     1400M    I            0       0
                                    7     1200M    IV           0       1
                  190525 May   2019 1     1100M    V            0       0
                                    2     1400M    M3y          0       0
                                    3     1100M    V            0       0
                                    4     1600M    I            0       0
                                    5     1400M    III          0       0
                                    6     1200M    IV           0       1
                                    7     1400M    IV           0       0
                  190526 May   2019 1     1400M    V            0       0
                                    2     1600M    IV           0       1
                                    3     1200M    III          0       0
                                    4     1400M    T 4y&o       0       0
                                    5     1200M    II           0       0
                                    6     1400M    IV           0       0
                                    7     1200M    M3y          0       0
                  190601 Jun   2019 1     1200M    IV           0       0
                                    2     1200M    IV           0       1
                                    3     1200M    M3y          0       0
                                    4     1200M    II           0       0
                                    5     1400M    I            0       0
                                    6     1200M    M3y          0       0
                  190602 Jun   2019 1     1600M    M3y          0       1
                                    2     1100M    V            0       0

f_r                                                        (2, 1)  (2, 2)  \
Venue Season Code Date   Month Year R No. Distance Class
BLR   BS18        180809 Aug   2018 1     1400M    V            1       0
                                    2     1600M    IV           1       0
                                    3     1100M    III          1       0
                                    4     1200M    II           0       1
                                    5     1400M    III          0       0
                                    6     1100M    III          0       1
                                    7     1200M    IV           0       0
                  180810 Aug   2018 1     1200M    V            0       0
                                    2     1100M    M3y          0       1
                                    3     1600M    III          0       0
                                    4     1400M    I            0       1
                                    5     1600M    V            0       0
                                    6     1400M    M3y          1       0
                                    7     1200M    IV           0       0
      BS19        190518 May   2018 1     1200M    M3y          1       0
                                    2     1600M    V            0       0
                                    3     1400M    III          0       1
                                    4     1200M    I            0       0
                                    5     1200M    M3y          0       1
                                    6     1400M    IV           0       0
                                    7     1100M    IV           0       0
                  190519 May   2018 1     1100M    M3y          0       1
                                    2     1200M    V            0       0
                                    3     1400M    II           1       0
                                    4     1400M    T 3y         0       0
                                    5     1200M    III          0       0
                                    6     1400M    I            0       0
                                    7     1200M    IV           0       0
                  190525 May   2019 1     1100M    V            0       1
                                    2     1400M    M3y          1       0
                                    3     1100M    V            0       0
                                    4     1600M    I            1       0
                                    5     1400M    III          1       0
                                    6     1200M    IV           0       0
                                    7     1400M    IV           0       0
                  190526 May   2019 1     1400M    V            0       1
                                    2     1600M    IV           0       0
                                    3     1200M    III          0       1
                                    4     1400M    T 4y&o       0       0
                                    5     1200M    II           0       1
                                    6     1400M    IV           0       1
                                    7     1200M    M3y          1       0
                  190601 Jun   2019 1     1200M    IV           0       1
                                    2     1200M    IV           0       0
                                    3     1200M    M3y          0       0
                                    4     1200M    II           0       1
                                    5     1400M    I            0       1
                                    6     1200M    M3y          0       1
                  190602 Jun   2019 1     1600M    M3y          0       0
                                    2     1100M    V            0       0

f_r                                                        (2, 3)  (2, 4)  \
Venue Season Code Date   Month Year R No. Distance Class
BLR   BS18        180809 Aug   2018 1     1400M    V            0       0
                                    2     1600M    IV           0       0
                                    3     1100M    III          0       0
                                    4     1200M    II           0       0
                                    5     1400M    III          0       1
                                    6     1100M    III          0       0
                                    7     1200M    IV           0       0
                  180810 Aug   2018 1     1200M    V            1       0
                                    2     1100M    M3y          0       0
                                    3     1600M    III          1       0
                                    4     1400M    I            0       0
                                    5     1600M    V            0       0
                                    6     1400M    M3y          0       0
                                    7     1200M    IV           1       0
      BS19        190518 May   2018 1     1200M    M3y          0       0
                                    2     1600M    V            0       1
                                    3     1400M    III          0       0
                                    4     1200M    I            0       0
                                    5     1200M    M3y          0       0
                                    6     1400M    IV           1       0
                                    7     1100M    IV           0       0
                  190519 May   2018 1     1100M    M3y          0       0
                                    2     1200M    V            1       0
                                    3     1400M    II           0       0
                                    4     1400M    T 3y         0       1
                                    5     1200M    III          0       1
                                    6     1400M    I            0       1
                                    7     1200M    IV           0       0
                  190525 May   2019 1     1100M    V            0       0
                                    2     1400M    M3y          0       0
                                    3     1100M    V            1       0
                                    4     1600M    I            0       0
                                    5     1400M    III          0       0
                                    6     1200M    IV           0       0
                                    7     1400M    IV           0       1
                  190526 May   2019 1     1400M    V            0       0
                                    2     1600M    IV           0       0
                                    3     1200M    III          0       0
                                    4     1400M    T 4y&o       0       1
                                    5     1200M    II           0       0
                                    6     1400M    IV           0       0
                                    7     1200M    M3y          0       0
                  190601 Jun   2019 1     1200M    IV           0       0
                                    2     1200M    IV           0       0
                                    3     1200M    M3y          0       1
                                    4     1200M    II           0       0
                                    5     1400M    I            0       0
                                    6     1200M    M3y          0       0
                  190602 Jun   2019 1     1600M    M3y          0       0
                                    2     1100M    V            1       0

f_r                                                        (3, 0)  (3, 1)  \
Venue Season Code Date   Month Year R No. Distance Class
BLR   BS18        180809 Aug   2018 1     1400M    V            1       0
                                    2     1600M    IV           1       0
                                    3     1100M    III          1       0
                                    4     1200M    II           1       0
                                    5     1400M    III          0       0
                                    6     1100M    III          0       0
                                    7     1200M    IV           0       0
                  180810 Aug   2018 1     1200M    V            0       1
                                    2     1100M    M3y          0       0

In [17]:
100*race_stats['F12'].value_counts().get(1,0)/len(race_stats)

12.693780776946927

In [18]:
for col in race_stats.columns[20:]:
    print("{}: {}".format(col,100*race_stats[col].value_counts().get(1,0)/len(race_stats)))

F12: 12.693780776946927
F13: 8.188947656392486
F14: 5.781506474557724
F21: 7.5323727886193685
F23: 3.7205909173809957
F24: 2.1885828925770565
F31: 4.431880357468539
F32: 2.991063286521977
F34: 1.8238190771475469
F41: 2.407441181834762
F42: 1.7143899325186942
F43: 1.477293452489513
F12|F21: 20.226153565566296
F13|F31: 12.620828013861026
F14|F41: 8.188947656392486
F23|F32: 6.711654203902973
F24|F42: 3.9029728250957505
F34|F43: 3.30111252963706
F1|F2: 58.3622104687215
F1|F3: 52.47127484953493
F1|F4: 47.328105051978845
F2|F3: 32.39102681014043
F2|F4: 27.2113806310414
F3|F4: 21.393397774940727
F1|F2|F3: 71.51194601495531
F1|F2|F4: 66.38701440817071
F1|F3|F4: 60.514316979755606
F2|F3|F4: 40.47054532190407
F1|F2|F3|F4: 79.53674995440453
F123: 3.9394492066387015
F124: 2.717490424949845
F132: 2.8086813788072225
F134: 1.4955316432609884
F142: 1.8420572679190224
F143: 1.513769834032464
F213: 2.1521065110341056
F214: 1.8055808863760714
F231: 1.5867225971183658
F234: 0.6565748677731169
F241: 0.4559547692868867
F243: 0.5471457231442641
F312: 1.5502462155754149
F314: 0.7112894400875434
F321: 1.0942914462885283
F324: 0.5289075323727886
F341: 0.5471457231442641
F342: 0.40124019697246033
F412: 0.8389567754878716
F413: 0.4924311508298377
F421: 0.5471457231442641
F423: 0.38300200620098485
F431: 0.310049243115083
F432: 0.5471457231442641
F1234: 0.32828743388655846
F1243: 0.2553346708006566
F1324: 0.20062009848623016
F1342: 0.14590552617180375
F1423: 0.09119095385737735
F1432: 0.10942914462885282
F2134: 0.20062009848623016
F2143: 0.09119095385737735
F2314: 0.07295276308590187
F2341: 0.07295276308590187
F2413: 0.036476381542950936
F2431: 0.018238190771475468
F3124: 0.07295276308590187
F3142: 0.018238190771475468
F3214: 0.05471457231442641
F3241: 0.036476381542950936
F3412: 0.05471457231442641
F3421: 0.0
F4123: 0.05471457231442641
F4132: 0.05471457231442641
F4213: 0.018238190771475468
F4231: 0.036476381542950936
F4312: 0.036476381542950936
F4321: 0.05471457231442641

In [19]:
race_stats.reset_index(inplace=True)

In [20]:
race_stats

f_r,Venue,Season Code,Date,Month,Year,R No.,Distance,Class,"(1, 0)","(1, 1)","(1, 2)","(1, 3)","(1, 4)","(2, 0)","(2, 1)","(2, 2)","(2, 3)","(2, 4)","(3, 0)","(3, 1)","(3, 2)","(3, 3)","(3, 4)","(4, 0)","(4, 1)","(4, 2)","(4, 3)","(4, 4)",F12,F13,F14,F21,F23,F24,F31,F32,F34,F41,F42,F43,F12|F21,F13|F31,F14|F41,F23|F32,F24|F42,F34|F43,F1|F2,F1|F3,F1|F4,F2|F3,F2|F4,F3|F4,F1|F2|F3,F1|F2|F4,F1|F3|F4,F2|F3|F4,F1|F2|F3|F4,F123,F124,F132,F134,F142,F143,F213,F214,F231,F234,F241,F243,F312,F314,F321,F324,F341,F342,F412,F413,F421,F423,F431,F432,F1234,F1243,F1324,F1342,F1423,F1432,F2134,F2143,F2314,F2341,F2413,F2431,F3124,F3142,F3214,F3241,F3412,F3421,F4123,F4132,F4213,F4231,F4312,F4321
0,BLR,BS18,180809,Aug,2018,1,1400M,V,0,0,1,0,0,0,1,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,1,1,0,1,1,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
1,BLR,BS18,180809,Aug,2018,2,1600M,IV,0,0,1,0,0,0,1,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,1,1,0,1,1,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
2,BLR,BS18,180809,Aug,2018,3,1100M,III,1,0,0,0,0,0,1,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,1,0,0,1,1,0,1,1,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
3,BLR,BS18,180809,Aug,2018,4,1200M,II,1,0,0,0,0,0,0,1,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
4,BLR,BS18,180809,Aug,2018,5,1400M,III,0,1,0,0,0,0,0,0,0,1,0,0,1,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,1,1,0,0,0,1,1,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5478,PUN,PR19,191026,OCT,2019,4,1400M,M3y,0,0,1,0,0,0,0,0,1,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,1,0,1,1,0,1,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
5479,PUN,PR19,191026,OCT,2019,5,2000M,T-4y&o,1,0,0,0,0,1,0,0,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
5480,PUN,PR19,191026,OCT,2019,6,1600M,IV,0,1,0,0,0,1,0,0,0,0,0,0,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,1,0,0,0,1,1,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
5481,PUN,PR19,191026,OCT,2019,7,1200M,IV,0,1,0,0,0,1,0,0,0,0,0,0,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,1,0,0,0,1,1,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
5482,PUN,PR19,191026,OCT,2019,8,1000M,V 5y&o,1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0

In [ ]:
for col in race_stats.columns[20:]:
    x=race_stats.loc[race_stats['F12']==1][['Venue', 'Season Code', 'Date', 'Month', 'Year', 'R No.', 'Distance', 'Class', 'F12']]
    combo_df = pd.merge(x, df, on=['Venue', 'Season Code', 'Date', 'Month', 'Year', 'R No.', 'Distance', 'Class'])

In [66]:
x=race_stats.loc[race_stats['F12']==1][['Venue', 'Season Code', 'Date', 'Month', 'Year', 'R No.', 'Distance', 'Class', 'F12']]

In [68]:
len(x)

696

In [67]:
combo_df = pd.merge(x, df, on=['Venue', 'Season Code', 'Date', 'Month', 'Year', 'R No.', 'Distance', 'Class'])
combo_df

,Venue,Season Code,Date,Month,Year,R No.,Distance,Class,F12,Sl,Season,NoR,F,H. No,RESULT,Race Time,Age,Wt,Dr,Sh,LBW,fav_num,Truth,f_r
0,KOL,KM18,180807,Aug,2018,3,1100M,IV,1,2949,MON,8,F2,2,2,0.604167,5y,62.5,5,S,0.00,2,True,"(2, 2)"
1,KOL,KM18,180807,Aug,2018,3,1100M,IV,1,2950,MON,8,F3,7,0,0.604167,4y,59.0,6,A,19.75,3,False,"(3, 0)"
2,KOL,KM18,180807,Aug,2018,3,1100M,IV,1,2951,MON,8,F1,8,1,0.604167,4y,56.5,3,A,0.00,1,True,"(1, 1)"
3,KOL,KM18,180807,Aug,2018,3,1100M,IV,1,2952,MON,8,F4,9,3,0.604167,4y,57.5,4,S,0.50,4,False,"(4, 3)"
4,MYS,MyS18,180808,Aug,2018,8,1200M,III,1,3001,SUM,8,F4,1,0,0.729167,6y,58.0,2,A,5.75,4,False,"(4, 0)"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2783,HYD,HM21,210926,SEP,2021,6,1400M,M3y,1,21452,Mon,8,F4,7,0,0.659722,4y,58.5,7,S,16.50,4,False,"(4, 0)"
2784,HYD,HM21,210926,SEP,2021,7,1800M,III 5y&o,1,21453,Mon,8,F1,8,1,0.684028,5y,60.0,11,S,0.00,1,True,"(1, 1)"
2785,HYD,HM21,210926,SEP,2021,7,1800M,III 5y&o,1,21454,Mon,8,F2,2,2,0.684028,5y,57.5,6,A,0.00,2,True,"(2, 2)"
2786,HYD,HM21,210926,SEP,2021,7,1800M,III 5y&o,1,21455,Mon,8,F3,9,4,0.684028,6y,55.5,4,S,1.50,3,False,"(3, 4)"
2787,HYD,HM21,210926,SEP,2021,7,1800M,III 5y&o,1,21456,Mon,8,F4,6,0,0.684028,5y,56.0,5,A,2.75,4,False,"(4, 0)"

In [69]:
age = []
sh = []
wt = []
initial = ["F12","RESULT"]
if age!=None:
    initial.append("Age")
if sh!=None:
    initial.append("Sh")
if wt!=None:
    initial.append("Wt")
initial

['F12', 'RESULT', 'Age', 'Sh', 'Wt']

In [79]:
pd.concat([combo_df.groupby(initial, as_index=True).size().unstack(fill_value=0),combo_df.groupby(initial, as_index=True).size().unstack(fill_value=0)])

Wt                 0.0   50.0  50.5  51.0  51.5  52.0  52.5  53.0  53.5  54.0  \
F12 RESULT Age Sh
1   0      2y  A      0     0     0     0     0     0     0     0     1     0
               S      0     0     0     0     0     0     0     0     4     0
           3y  A      0     0     2     0     0     1     3     2    19     7
               AS     0     0     0     0     0     0     0     0     0     0
               S      0     4     0     1     2     2     3     6    13     6
...                 ...   ...   ...   ...   ...   ...   ...   ...   ...   ...
    4      5y  S      0     0     0     0     1     0     2     1     1     0
           6y  A      0     0     0     0     0     0     0     0     0     0
               S      0     0     0     0     0     0     0     0     0     0
           7y  A      0     0     0     0     0     0     0     0     0     0
               S      0     0     0     0     0     0     0     0     0     0

Wt                 54.5  55.0  55.5  56.0  56.5  57.0  57.5  58.0  58.5  59.0  \
F12 RESULT Age Sh
1   0      2y  A      0     2     1     0     0     0     0     0     0     0
               S      0     4     0     0     0     0     0     0     0     0
           3y  A     29    25     7    45     3    14     0     5     5     0
               AS     0     0     0     0     1     0     0     0     0     0
               S     26    21     3    31     1     8     4     1     1     3
...                 ...   ...   ...   ...   ...   ...   ...   ...   ...   ...
    4      5y  S      0     0     0     0     0     1     1     0     1     1
           6y  A      0     0     0     0     0     0     0     0     0     0
               S      0     0     1     0     1     0     0     0     1     0
           7y  A      1     0     0     0     0     0     0     0     0     0
               S      0     0     0     0     0     0     0     0     0     0

Wt                 59.5  60.0  60.5  61.0  61.5  62.0  62.5  63.0  63.5  64.0  \
F12 RESULT Age Sh
1   0      2y  A      0     0     0     0     0     0     0     0     0     0
               S      0     0     0     0     0     0     0     0     0     0
           3y  A      5     9     3     6     4     6     7     0     0     0
               AS     0     0     0     0     0     0     0     0     0     0
               S      4     4     0     3     3     2     1     0     0     0
...                 ...   ...   ...   ...   ...   ...   ...   ...   ...   ...
    4      5y  S      0     1     0     0     0     0     0     0     0     0
           6y  A      0     1     0     0     0     0     0     0     0     0
               S      0     0     0     0     0     1     1     0     0     0
           7y  A      0     0     0     0     0     0     0     0     0     0
               S      0     0     1     0     0     0     0     0     0     0

Wt                 66.0  66.5
F12 RESULT Age Sh
1   0      2y  A      0     0
               S      0     0
           3y  A      0     0
               AS     0     0
               S      0     0
...                 ...   ...
    4      5y  S      0     0
           6y  A      0     0
               S      0     0
           7y  A      0     0
               S      0     0

[126 rows x 32 columns]

In [26]:
race_stats.sort_values(['Date','Season Code','R No.'], inplace=True)

In [27]:
race_stats[-100:]

f_r,Venue,Season Code,Date,Month,Year,R No.,Distance,Class,"(1, 0)","(1, 1)","(1, 2)","(1, 3)","(1, 4)","(2, 0)","(2, 1)","(2, 2)","(2, 3)","(2, 4)","(3, 0)","(3, 1)","(3, 2)","(3, 3)","(3, 4)","(4, 0)","(4, 1)","(4, 2)","(4, 3)","(4, 4)",F12,F13,F14,F21,F23,F24,F31,F32,F34,F41,F42,F43,F12|F21,F13|F31,F14|F41,F23|F32,F24|F42,F34|F43,F1|F2,F1|F3,F1|F4,F2|F3,F2|F4,F3|F4,F1|F2|F3,F1|F2|F4,F1|F3|F4,F2|F3|F4,F1|F2|F3|F4,F123,F124,F132,F134,F142,F143,F213,F214,F231,F234,F241,F243,F312,F314,F321,F324,F341,F342,F412,F413,F421,F423,F431,F432,F1234,F1243,F1324,F1342,F1423,F1432,F2134,F2143,F2314,F2341,F2413,F2431,F3124,F3142,F3214,F3241,F3412,F3421,F4123,F4132,F4213,F4231,F4312,F4321
2322,HYD,O21,210909,SEP,2021,3,1200M,IV,0,0,0,0,1,0,1,0,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0,1,0,0,1,1,0,1,1,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
2323,HYD,O21,210909,SEP,2021,4,1000M,III,0,1,0,0,0,0,0,0,1,0,0,0,1,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,1,1,0,0,0,1,1,1,0,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
2324,HYD,O21,210909,SEP,2021,5,1600M,V,0,0,0,0,1,0,0,1,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
2325,HYD,O21,210909,SEP,2021,6,1600M,IV,0,0,0,1,0,0,1,0,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0,1,0,0,1,1,0,1,1,0,1,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
2326,HYD,O21,210909,SEP,2021,7,1000M,III,0,1,0,0,0,0,0,0,1,0,0,0,1,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,1,1,0,0,0,1,1,1,0,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5058,OTY,O21,210930,SEP,2021,4,NA,NA,1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
5059,OTY,O21,210930,SEP,2021,5,NA,NA,1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
5060,OTY,O21,210930,SEP,2021,6,NA,NA,1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
5061,OTY,O21,210930,SEP,2021,7,NA,NA,1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
5062,OTY,O21,210930,SEP,2021,8,NA,NA,1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0

In [28]:
race_stats["Class"]

2334      V
2335     IV
2336     IV
2337    M3y
2338     II
       ...
5058     NA
5059     NA
5060     NA
5061     NA
5062     NA
Name: Class, Length: 5483, dtype: object

In [29]:
blr=race_stats[race_stats['Venue']=='BLR']

In [30]:
blr['F12'].value_counts()

0    640
1    105
Name: F12, dtype: int64

In [31]:
def maxwinstreaks(dfff, n=1):
    wstreak = 0
    maxwstreak = 0
    for i in dfff:
        if i != n:
            if wstreak > maxwstreak:
                maxwstreak = wstreak
            wstreak = 0
        if i == n:
            wstreak += 1
    if wstreak > maxwstreak:
        maxwstreak = wstreak

    return maxwstreak

def maxlosestreaks(dfff, n=1):
    lstreak = 0
    maxlstreak = 0
    for i in dfff:
        if i != n:
            lstreak += 1
        if i == n:
            if lstreak > maxlstreak:
                maxlstreak = lstreak
            lstreak = 0
    if lstreak > maxlstreak:
        maxlstreak = lstreak

    return maxlstreak

In [32]:
foo = ['F1', 'F2', 'F3', 'F4']
pl = [1, 2, 3, 4, 0]
n = blrdf.groupby(["F","RESULT"], as_index=True).size().unstack(fill_value=0)
mis_col = [i for i in pl if i not in n.columns]
for col in mis_col:
    n[col] = [0] * len(n)
n = n[pl]
m = blrdf.groupby(["F"], as_index=True).size().to_frame()
k = blrdf.groupby(["F"], as_index=True)['RESULT'].agg([maxwinstreaks, maxlosestreaks])
k.rename(columns={'maxwinstreaks': 'LWS', 'maxlosestreaks': 'LLS'}, inplace=True)
fodf = pd.concat([n, m, k], axis=1)
fodf.columns = [1,2,3,4,0,'TR','LWS','LLS']
fodf.rename(columns={1:"W", 2:"SHP", 3:"THP", 'maxwinstreaks':'LWS', 'maxlosestreaks':'LLS'}, inplace=True)
fodf["W%"]=((fodf["W"]/fodf['TR'])*100).round(2)
fodf["SHP%"]=((fodf["SHP"]/fodf['TR'])*100).round(2)
fodf["THP%"]=((fodf["THP"]/fodf['TR'])*100).round(2)
fodf["Plc%"]=(((fodf["W"]+fodf["SHP"]+fodf["THP"])/fodf['TR'])*100).round(2)
fodf["Plc"]=fodf["W"]+fodf["SHP"]+fodf["THP"]
fodf["BO"]=fodf["TR"]-fodf["Plc"]
# fodf["TR%"] = ((fodf["TR"] / len(df)) * 100 *4).round(2)
f = [i for i in foo if i in fodf.index]
fodf = fodf.reindex(f)
fodf = fodf[['TR','W','W%','SHP','SHP%','THP','THP%','Plc','Plc%','BO','LWS','LLS']]
fodf

NameError: name 'blrdf' is not defined

In [ ]:
len(df)

In [ ]:
blrdf=df[df['Venue']=='BLR']

In [ ]:
foo = ['F1', 'F2', 'F3', 'F4']
pl = [1, 2, 3, 4, 0]
n = df.groupby(["F","Season Code","RESULT"], as_index=True).size().unstack(fill_value=0)
mis_col = [i for i in pl if i not in n.columns]
for col in mis_col:
    n[col] = [0] * len(n)
n = n[pl]
m = df.groupby(["F","Season Code"], as_index=True).size().to_frame()
k = df.groupby(["F","Season Code"], as_index=True)['RESULT'].agg([maxwinstreaks, maxlosestreaks])
k.rename(columns={'maxwinstreaks': 'LWS', 'maxlosestreaks': 'LLS'}, inplace=True)
fseasondf = pd.concat([n, m, k], axis=1)

fseasondf.columns = [1,2,3,4,0,'TR','LWS','LLS']
fseasondf.rename(columns={1:"W", 2:"SHP", 3:"THP", 'maxwinstreaks':'LWS', 'maxlosestreaks':'LLS'}, inplace=True)
fseasondf["W%"]=((fseasondf["W"]/fseasondf['TR'])*100).round(2)
fseasondf["SHP%"]=((fseasondf["SHP"]/fseasondf['TR'])*100).round(2)
fseasondf["THP%"]=((fseasondf["THP"]/fseasondf['TR'])*100).round(2)
fseasondf["Plc%"]=(((fseasondf["W"]+fseasondf["SHP"]+fseasondf["THP"])/fseasondf['TR'])*100).round(2)
fseasondf["Plc"]=fseasondf["W"]+fseasondf["SHP"]+fseasondf["THP"]
fseasondf["BO"]=fseasondf["TR"]-fseasondf["Plc"]

# fodf["TR%"] = ((fodf["TR"] / len(df)) * 100 *4).round(2)
# f = [i for i in foo if i in fseasondf.index]
# fseasondf = fseasondf.reindex(f)
fseasondf = fseasondf[['TR','W','W%','SHP','SHP%','THP','THP%','Plc','Plc%','BO','LWS','LLS']]
fseasondf

In [ ]:
fseasondf.loc['F1']

In [ ]:
indexes_names = fseasondf.index.names
a=fseasondf.reset_index().to_json(orient='split')
indexes_names

In [ ]:
b=pd.read_json(a ,orient = 'split').set_index(indexes_names)
b

In [ ]:
foo = ['F1', 'F2', 'F3', 'F4']
pl = [1, 2, 3, 4, 0]
n = df.groupby(["F","Distance","RESULT"], as_index=True).size().unstack(fill_value=0)
mis_col = [i for i in pl if i not in n.columns]
for col in mis_col:
    n[col] = [0] * len(n)
n = n[pl]
m = df.groupby(["F","Distance"], as_index=True).size().to_frame()
k = df.groupby(["F","Distance"], as_index=True)['RESULT'].agg([maxwinstreaks, maxlosestreaks])
k.rename(columns={'maxwinstreaks': 'LWS', 'maxlosestreaks': 'LLS'}, inplace=True)
fdistancedf = pd.concat([n, m, k], axis=1)

fdistancedf.columns = [1,2,3,4,0,'TR','LWS','LLS']
fdistancedf.rename(columns={1:"W", 2:"SHP", 3:"THP", 'maxwinstreaks':'LWS', 'maxlosestreaks':'LLS'}, inplace=True)
fdistancedf["W%"]=((fdistancedf["W"]/fdistancedf['TR'])*100).round(2)
fdistancedf["SHP%"]=((fdistancedf["SHP"]/fdistancedf['TR'])*100).round(2)
fdistancedf["THP%"]=((fdistancedf["THP"]/fdistancedf['TR'])*100).round(2)
fdistancedf["Plc%"]=(((fdistancedf["W"]+fdistancedf["SHP"]+fdistancedf["THP"])/fdistancedf['TR'])*100).round(2)
fdistancedf["Plc"]=fdistancedf["W"]+fdistancedf["SHP"]+fdistancedf["THP"]
fdistancedf["BO"]=fdistancedf["TR"]-fdistancedf["Plc"]

# fodf["TR%"] = ((fodf["TR"] / len(df)) * 100 *4).round(2)
# f = [i for i in foo if i in fdistancedf.index]
# fdistancedf = fdistancedf.reindex(f)
fdistancedf = fdistancedf[['TR','W','W%','SHP','SHP%','THP','THP%','Plc','Plc%','BO','LWS','LLS']]
fdistancedf

In [ ]:
foo = ['F1', 'F2', 'F3', 'F4']
pl = [1, 2, 3, 4, 0]
n = df.groupby(["F","Class","RESULT"], as_index=True).size().unstack(fill_value=0)
mis_col = [i for i in pl if i not in n.columns]
for col in mis_col:
    n[col] = [0] * len(n)
n = n[pl]
m = df.groupby(["F","Class"], as_index=True).size().to_frame()
k = df.groupby(["F","Class"], as_index=True)['RESULT'].agg([maxwinstreaks, maxlosestreaks])
k.rename(columns={'maxwinstreaks': 'LWS', 'maxlosestreaks': 'LLS'}, inplace=True)
fclassdf = pd.concat([n, m, k], axis=1)

fclassdf.columns = [1,2,3,4,0,'TR','LWS','LLS']
fclassdf.rename(columns={1:"W", 2:"SHP", 3:"THP", 'maxwinstreaks':'LWS', 'maxlosestreaks':'LLS'}, inplace=True)
fclassdf["W%"]=((fclassdf["W"]/fclassdf['TR'])*100).round(2)
fclassdf["SHP%"]=((fclassdf["SHP"]/fclassdf['TR'])*100).round(2)
fclassdf["THP%"]=((fclassdf["THP"]/fclassdf['TR'])*100).round(2)
fclassdf["Plc%"]=(((fclassdf["W"]+fclassdf["SHP"]+fclassdf["THP"])/fclassdf['TR'])*100).round(2)
fclassdf["Plc"]=fclassdf["W"]+fclassdf["SHP"]+fclassdf["THP"]
fclassdf["BO"]=fclassdf["TR"]-fclassdf["Plc"]

# fodf["TR%"] = ((fodf["TR"] / len(df)) * 100 *4).round(2)
# f = [i for i in foo if i in fclassdf.index]
# fclassdf = fclassdf.reindex(f)
fclassdf = fclassdf[['TR','W','W%','SHP','SHP%','THP','THP%','Plc','Plc%','BO','LWS','LLS']]
fclassdf

In [ ]:
combination=['F1']
match = ['F1']

In [ ]:
set(combination) == set(match)