In [1]:
import numpy as np
import pandas as pd

In [2]:
pd.set_option('display.max_columns', None)
# pd.set_option('display.max_rows', None)

In [3]:
# data = pd.concat(pd.read_excel(r'C:\Users\Testing\NEW METHOD FILE.xlsx', sheet_name=None), ignore_index=True)
# data = pd.read_excel(r'C:\Users\Testing\Downloads\NEW METHOD 210805 (1).xlsx')

data = pd.read_excel(r'C:\Users\Testing\Downloads\ALL METHODS - MASTER FILE (1).xlsb', engine='pyxlsb')
data['Date']= pd.to_datetime(data['Date'], unit='D', origin='1899-12-30T00:00:00.000000000')
data.rename(columns = {'CENTER':'Centre', 'VENUE ID': 'Venue ID', 'R No #': 'Race No', 'RES': 'Result', 'CLASS': 'Class', 'DIST': 'Dist'}, inplace = True)
data.Dist.replace([np.nan],[0],inplace=True)
data.Class.replace([np.nan],['-'],inplace=True)
data.Jockey.replace([np.nan],['-'],inplace=True)
data.Trainer.replace([np.nan],['-'],inplace=True)
data['Horse Name'].replace([np.nan],['-'],inplace=True)
data['Sr #'] = [x+1 for x in data.index]
data['Rtg'] = [0]*len(data)
data['Penalty'] = [0]*len(data)
data['Time in S'] = [0]*len(data)
data['Time'] = [0]*len(data)
data['Odds'] = [0]*len(data)

data.rename(columns = {'Center':'Season', 'Horse Name': 'Horse', 'Dist': 'Distance', }, inplace = True)

data.Age.replace([np.nan, '3y', '5y', '4y', '6y', '7y', '8y', '9y', '2y', '0y', '14y', '10y', '11y', '12y', '1y'],[0, 3, 5, 4, 6, 7, 8, 9, 2, 0, 14, 10, 11, 12, 1],inplace=True)
data.Result.replace(['DNC', 'NC', 'DNF', 'DR', 'W'],[0,0,0,0,0], inplace=True)

# data['combined_data'] = list(zip(data.Age, data.Result))
# data['Dr53'] = ((data['combined_data']==(5,3)).replace([False, True], [0, 1]))*data['Dr']
# data['Dr54'] = ((data['combined_data']==(5,4)).replace([False, True], [0, 1]))*data['Dr']

# data['combined_data'] = list(zip(data.Dr, data.LBW))
# data['LBW2'] = ((data['Dr']>=10).replace([False, True], [0, 1]))*data['LBW']

data['RunNo.']=[-1]*len(data)

data['Dr'].replace([np.nan], [0], inplace=True)
data['LBW'].replace([np.nan, 'W'], [0,0], inplace=True)
try:
    data['Time in S'].replace([np.nan, 'DNF'], [0,0], inplace=True)
except:
    pass
data['Dr'] = data.Dr.astype(int)

data = data.loc[data['Distance']==1200]

data.drop(columns=['Time'], inplace=True)
new = data['Venue ID'].str.split("=", n = 1, expand = True)
data['Venue ID'] = new[1]
data['Venue ID'] = data['Venue ID'].astype(int)
data['Venue Name'] = data['Venue ID'].replace([1,2,3,4,7,8,9,10,11], ['KOL', 'MUM', 'BLR', 'CHE', 'DEL', 'MYS', 'OOT', 'PUN', 'HYD'])

In [4]:
df = data
df

,C-Sr#,Date,Season,Centre,Venue ID,Class,Distance,Race No,Horse,Age,Jockey,Trainer,Wt,Dr,Sh,Result,LBW,Sr #,Rtg,Penalty,Time in S,Odds,RunNo.,Venue Name
0,B1,2008-05-17,BS08,BLR,3,3y,1200.0,1,AQUITAINE,3,M NARREDU,-,54.5,1,A,1,0.00,1,0,0,0,0,-1,BLR
1,B2,2008-05-17,BS08,BLR,3,3y,1200.0,1,PLEASURING,3,B PRAKASH,S GANAPATHY,54.5,8,S,2,7.50,2,0,0,0,0,-1,BLR
2,B3,2008-05-17,BS08,BLR,3,3y,1200.0,1,MINT,3,A IMRAN KHAN,J S DHARIWAL,54.5,11,A,3,10.25,3,0,0,0,0,-1,BLR
3,B4,2008-05-17,BS08,BLR,3,3y,1200.0,1,YOU BEAUTY,3,Ms LISA JONES,-,54.5,10,A,4,12.25,4,0,0,0,0,-1,BLR
4,B5,2008-05-17,BS08,BLR,3,3y,1200.0,1,JUST GREAT,3,D GNANESHWAR,AMIT CADDY,56.0,6,S,5,12.25,5,0,0,0,0,-1,BLR
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
241557,M29429,2021-04-04,M20,MUM,2,IV 5y&o,1200.0,202,DIVINE GLORY,5,Bhawani Singh,Altaf Hussain,59.0,9,A,10,8.25,241558,0,0,0,0,-1,MUM
241558,M29430,2021-04-04,M20,MUM,2,IV 5y&o,1200.0,202,UNTITLED,8,Hanumant Singh,H J Antia,57.5,1,A,11,9.50,241559,0,0,0,0,-1,MUM
241559,M29431,2021-04-04,M20,MUM,2,IV 5y&o,1200.0,202,AIRMAX,5,H Zeeshan,Adil Dajee,50.0,5,A,12,11.00,241560,0,0,0,0,-1,MUM
241560,M29432,2021-04-04,M20,MUM,2,IV 5y&o,1200.0,202,SLAM DUNK,8,D R Shubham,H J Antia,59.5,6,A,13,22.25,241561,0,0,0,0,-1,MUM
241561,M29433,2021-04-04,M20,MUM,2,IV 5y&o,1200.0,202,SENIORITY,5,Withdrawn,Imtiaz A Sait,53.5,7,A,0,100.00,241562,0,0,0,0,-1,MUM

In [5]:
race_stats = df.groupby(["Date", "Season", "Race No", "Result"], as_index=True).size().unstack(
    fill_value=0)
# race_stats = pd.concat([m,l], axis=1)
race_stats.reset_index(inplace=True)
race_stats.index = np.arange(1, len(race_stats) + 1)
race_stats

Result,Date,Season,Race No,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22
1,2008-05-17,BS08,1,0,1,1,1,1,1,1,1,1,1,1,1,1,0,0,0,0,0,0,0,0,0,0
2,2008-05-17,BS08,3,0,1,1,1,1,1,1,1,1,1,1,1,1,0,0,0,0,0,0,0,0,0,0
3,2008-05-17,BS08,6,0,1,1,1,1,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
4,2008-05-17,BS08,8,0,1,1,1,1,1,1,1,1,1,1,1,1,0,0,0,0,0,0,0,0,0,0
5,2008-05-18,BS08,13,0,1,1,1,1,1,1,1,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5428,2021-09-06,HM21,73,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,0,0,0,0,0,0,0,0
5429,2021-09-06,HM21,75,0,1,1,1,1,1,1,1,1,1,1,1,1,1,0,0,0,0,0,0,0,0,0
5430,2021-11-01,BW20,2,0,1,1,1,1,1,1,1,1,1,1,1,1,0,0,0,0,0,0,0,0,0,0
5431,2021-11-01,BW20,4,1,1,1,1,1,1,1,1,1,1,1,1,0,0,0,0,0,0,0,0,0,0,0
5432,2021-11-01,BW20,5,0,1,1,1,1,1,1,1,1,1,1,1,1,0,0,0,0,0,0,0,0,0,0

In [7]:
qualified_horses = df.loc[(df['Dr']>=10) & (df['LBW']>=3.5) & (df['LBW']<=4)][['Horse', 'Date', 'Season', 'Race No', 'Sr #', 'Trainer', 'Rtg', 'Class', 'Distance','Age',
 'Wt', 'Jockey', 'Dr', 'Sh', 'Result', 'LBW', 'Penalty', 'Time in S', 'RunNo.']]
qualified_horses.index = np.arange(1, len(qualified_horses) + 1)

qualified_horses['LBW'] = round(qualified_horses['LBW'],2)
qualified_horses['Time'] = round(qualified_horses['Time in S'], 3)
qualified_horses.head(50)

,Horse,Date,Season,Race No,Sr #,Trainer,Rtg,Class,Distance,Age,Wt,Jockey,Dr,Sh,Result,LBW,Penalty,Time in S,RunNo.,Time
1,ADORABELLA,2008-07-19,BS08,152,1493,NEIL DARASHAH,0,III,1200.0,4,60.0,D GNANESHWAR,10,A,7,3.75,0,0,-1,0
2,STAR SPEED,2008-11-08,BW08,14,2177,S PADMANABHAN,0,III,1200.0,3,58.0,K P G APPU,11,A,2,3.75,0,0,-1,0
3,DOCK OF BAY,2008-12-05,BW08,55,2603,IRFAN GHATALA,0,III,1200.0,4,59.0,M NARREDU,10,A,3,3.50,0,0,-1,0
4,BROTHERS IN ARMS,2008-12-26,BW08,80,2848,NEIL DARASHAH,0,IV,1200.0,5,56.0,SAMUEL FARGEAT,11,A,2,3.50,0,0,-1,0
5,SULTAN MIRZA,2009-01-02,BW08,92,2987,-,0,IV,1200.0,4,56.5,A ASHOK KUMAR,10,A,3,3.50,0,0,-1,0
6,SPICY STAR,2009-01-02,BW08,95,3017,NEIL DARASHAH,0,III,1200.0,4,58.5,SAMUEL FARGEAT,12,A,3,3.75,0,0,-1,0
7,ALYCIAA,2009-01-03,BW08,105,3121,S INAYATHULLA,0,IV,1200.0,5,61.0,A ASHOK KUMAR,12,S,4,4.00,0,0,-1,0
8,MARCEGALIA,2009-01-23,BW08,128,3370,J S DHARIWAL,0,III,1200.0,4,56.0,D GNANESHWAR,10,A,3,3.75,0,0,-1,0
9,MOVIE QUEEN,2009-02-08,BW08,149,3598,B PUTTANNA,0,III,1200.0,5,55.0,C KRISHNAN,10,A,3,4.00,0,0,-1,0
10,BRUNETTA,2009-03-14,BW08,213,4242,IRFAN GHATALA,0,3y,1200.0,3,53.5,VINOD SHINDE,11,A,4,3.75,0,0,-1,0
11,RAIDER'S SUN,2009-03-27,BW08,240,4503,MOHD A ABBAS,0,III,1200.0,5,62.5,SHANTH KUMAR,12,S,4,4.00,0,0,-1,0
12,WAR CHILD,2009-05-17,BS09,16,4807,DARIUS BYRAMJI,0,III,1200.0,5,57.0,S MALLIKARJUN,10,A,6,4.00,0,0,-1,0
13,MONARCHIAL,2009-05-23,BS09,20,4854,V LOKANATH,0,IV,1200.0,4,58.0,S SHIVA KUMAR,11,S,5,3.75,0,0,-1,0
14,CROWNING GLORY,2009-05-30,BS09,39,5050,V LOKANATH,0,IV,1200.0,3,52.5,V R JAGADEESH,12,S,6,4.00,0,0,-1,0
15,SNOB VALUE,2009-06-06,BS09,53,5197,M B MANGALORKAR,0,II,1200.0,6,54.5,HARISH,10,A,10,3.75,0,0,-1,0
16,CLASSIC CONCEPT,2009-07-19,BS09,154,6221,RAVI SHANKER S,0,3y,1200.0,3,56.0,S JOHN,11,A,5,3.50,0,0,-1,0
17,FREEDOM FIGHTER,2009-07-25,BS09,162,6300,F SIRAJUDDIN,0,V,1200.0,4,59.0,MOHAMMED SHOAIB,10,S,7,4.00,0,0,-1,0
18,PHOENIX REACH,2009-08-06,BS09,198,6657,S GANAPATHY,0,II,1200.0,4,59.5,A IMRAN KHAN,11,S,4,3.50,0,0,-1,0
19,SNOW PEAKS,2009-11-14,BW09,21,7019,S DOMINIC,0,IV,1200.0,3,57.0,K P G APPU,11,S,3,3.50,0,0,-1,0
20,ENDURING SPEED,2009-11-21,BW09,39,7200,S DOMINIC,0,IV,1200.0,3,53.0,KHURSHAD ALAM,10,A,3,3.75,0,0,-1,0
21,SARATOGA,2009-12-04,BW09,52,7339,S BRITTO,0,3y,1200.0,3,55.5,SHOBHAN BABU,12,S,5,3.50,0,0,-1,0
22,DREAM PARK,2010-01-01,BW09,105,7869,NEIL DARASHAH,0,III,1200.0,4,59.5,SURAJ NARREDU,12,A,2,4.00,0,0,-1,0
23,DAY TRADER,2010-02-27,BW09,207,8902,J S DHARIWAL,0,3y,1200.0,3,55.0,MOHAMMED SHOAIB,11,A,3,3.75,0,0,-1,0
24,VOICE OF INDIA,2010-03-12,BW09,222,9066,SHARAT KUMAR,0,II,1200.0,5,58.0,S JOHN,10,S,5,3.75,0,0,-1,0
25,THE SPARTAN,2010-03-26,BW09,251,9337,SHARAT KUMAR,0,II,1200.0,5,55.0,AFSAR KHAN,12,S,5,4.00,0,0,-1,0
26,POETIC,2010-03-26,BW09,253,9359,KARAN SINGH,0,III,1200.0,5,61.0,VIVEK,10,S,4,4.00,0,0,-1,0
27,SUNNYLAND,2010-06-05,BS10,42,10064,WARREN SINGH,0,III,1200.0,6,59.5,AHSAN QURESHI,12,S,4,3.50,0,0,-1,0
28,D'ARTAGNAN,2010-06-06,BS10,48,10126,S PADMANABHAN,0,4y&o,1200.0,4,56.5,-,12,A,5,3.75,0,0,-1,0
29,SHOWHORSE,2010-06-12,BS10,54,10196,WARREN SINGH,0,IV,1200.0,6,59.0,P MANI,12,S,6,3.50,0,0,-1,0
30,FORTUNE QUEEN,2010-07-04,BS10,120,10844,PRASANNA KUMAR,0,II,1200.0,5,53.5,CH K CHARY,10,S,7,4.00,0,0,-1,0
31,SHE'S FOR CASH,2010-07-17,BS10,145,11088,J S PILLAY,0,IV,1200.0,5,62.5,M D PRAVEEN,10,S,4,3.75,0,0,-1,0
32,LUCKYNUMBERSLEVIN,2011-02-25,BW10,210,13675,HIDAYAT KHAN,0,III,1200.0,7,55.0,VIVEK,10,A,6,3.50,0,0,-1,0
33,SILVER COURT,2011-03-18,BW10,244,14018,V LOKANATH,0,V,1200.0,4,61.0,B SREEKANTH,10,S,2,3.50,0,0,-1,0
34,HILLINGDON,2011-03-25,BW10,255,14124,IRFAN GHATALA,0,3y,1200.0,3,55.0,B L PASWAN,10,A,2,3.50,0,0,-1,0
35,A GAME TO REMEMBER,2011-03-26,BW10,272,14318,WARREN SINGH,0,IV,1200.0,4,51.5,M J GAUTAM RAJ URS,12,A,5,4.00,0,0,-1,0
36,STORMYRED,2011-03-26,BW10,272,14319,SHARAT KUMAR,0,IV,1200.0,4,60.5,IRVAN SINGH,11,S,6,4.00,0,0,-1,0
37,HILLSTONE,2011-05-28,BS11,41,14732,IRFAN GHATALA,0,T-M 3y,1200.0,3,56.0,K G STEYN,11,A,3,3.50,0,0,-1,0
38,CHERRY HILL,2011-05-28,BS11,41,14733,L D SILVA,0,T-M 3y,1200.0,3,56.0,NEERAJ RAWAL,12,A,4,3.50,0,0,-1,0
39,STAR PRESENCE,2011-05-29,BS11,48,14803,S NARREDU,0,III,1200.0,5,61.5,D K ASHISH,12,A,3,4.00,0,0,-1,0
40,MAKE MY DAY,2011-11-07,BW11,6,16748,R R BYRAMJI,0,II,1200.0,4,53.0,P TREVOR,11,A,2,3.50,0,0,-1,0
41,SABALA,2011-11-18,BW11,31,16984,B PUTTANNA,0,V,1200.0,4,55.5,Y S SRINATH,11,S,5,3.75,0,0,-1,0
42,STAR OF DESIRE,2011-11-26,BW11,41,17083,HIDAYAT KHAN,0,III,1200.0,4,55.5,N RAJESH,10,S,3,3.50,0,0,-1,0
43,SIMPLY PHENOMENAL,2011-11-26,BW11,44,17115,S NARREDU,0,III,1200.0,5,60.5,HARISH,10,A,2,4.00,0,0,-1,0
44,YOURE CHILUBULI,2012-02-24,BW11,212,18638,PRADEEP ANNAIAH,0,IV,1200.0,6,60.0,SURAJ NARREDU,11,A,2,3.50,0,0,-1,0
45,SCARLETTE,2012-02-25,BW11,222,18746,S S ATTAOLLAHI,0,II,1200.0,5,56.5,ANTHONY CRASTUS,11,A,5,4.00,0,0,-1,0
46,LA CLIQUE,2012-03-30,BW11,298,19512,SHARAT KUMAR,0,IV,1200.0,5,58.5,IRVAN SINGH,10,S,4,3.75,0,0,-1,0
47,FOSWELL,2012-05-20,BS12,16,19812,J S DHARIWAL,0,III,1200.0,5,60.5,Y S SRINATH,11,A,3,3.75,0,0,-1,0
48,SUPERB STYLE,2012-06-02,BS12,44,20099,SHARAT KUMAR,0,III,1200.0,6,62.5,H G RATHOD,11,S,4,3.75,0,0,-1,0
49,SUCCESSOR,2012-06-03,BS12,51,20170,NEIL DARASHAH,0,T-M 4y&o,1200.0,7,56.0,C ALFORD,11,A,8,3.50,0,0,-1,0
50,CARIBBEAN QUEEN,2012-06-03,BS12,51,20172,P SHROFF,0,T-M 4y&o,1200.0,5,53.5,N S PARMAR,10,A,10,4.00,0,0,-1,0

In [8]:
qualifying_races = qualified_horses[["Date", "Season", "Race No"]]
qualifying_races

          Date Season  Race No
1   2008-07-19   BS08      152
2   2008-11-08   BW08       14
3   2008-12-05   BW08       55
4   2008-12-26   BW08       80
5   2009-01-02   BW08       92
..         ...    ...      ...
700 2021-01-15    M20       88
701 2021-01-24    M20      100
702 2021-01-29    M20      118
703 2021-02-28    M20      144
704 2021-03-14    M20      166

[704 rows x 3 columns]

In [12]:
qualifying_races_detailed = pd.merge(qualifying_races, df, on=["Date", "Season", "Race No"])
qualifying_races_detailed.set_index(["Date", "Season", "Race No"], inplace=True)
qualifying_races_detailed[20:80]

                           C-Sr# Centre  Venue ID Class  Distance  \
Date       Season Race No
2008-11-08 BW08   14       B2184    BLR         3   III    1200.0
                  14       B2185    BLR         3   III    1200.0
                  14       B2186    BLR         3   III    1200.0
                  14       B2187    BLR         3   III    1200.0
2008-12-05 BW08   55       B2601    BLR         3   III    1200.0
                  55       B2602    BLR         3   III    1200.0
                  55       B2603    BLR         3   III    1200.0
                  55       B2604    BLR         3   III    1200.0
                  55       B2605    BLR         3   III    1200.0
                  55       B2606    BLR         3   III    1200.0
                  55       B2607    BLR         3   III    1200.0
                  55       B2608    BLR         3   III    1200.0
                  55       B2609    BLR         3   III    1200.0
                  55       B2610    BLR         3   III    1200.0
                  55       B2611    BLR         3   III    1200.0
                  55       B2612    BLR         3   III    1200.0
2008-12-26 BW08   80       B2847    BLR         3    IV    1200.0
                  80       B2848    BLR         3    IV    1200.0
                  80       B2849    BLR         3    IV    1200.0
                  80       B2850    BLR         3    IV    1200.0
                  80       B2851    BLR         3    IV    1200.0
                  80       B2852    BLR         3    IV    1200.0
                  80       B2853    BLR         3    IV    1200.0
                  80       B2854    BLR         3    IV    1200.0
                  80       B2855    BLR         3    IV    1200.0
                  80       B2856    BLR         3    IV    1200.0
                  80       B2857    BLR         3    IV    1200.0
                  80       B2858    BLR         3    IV    1200.0
2009-01-02 BW08   92       B2985    BLR         3    IV    1200.0
                  92       B2986    BLR         3    IV    1200.0
                  92       B2987    BLR         3    IV    1200.0
                  92       B2988    BLR         3    IV    1200.0
                  92       B2989    BLR         3    IV    1200.0
                  92       B2990    BLR         3    IV    1200.0
                  92       B2991    BLR         3    IV    1200.0
                  92       B2992    BLR         3    IV    1200.0
                  92       B2993    BLR         3    IV    1200.0
                  92       B2994    BLR         3    IV    1200.0
                  92       B2995    BLR         3    IV    1200.0
                  95       B3015    BLR         3   III    1200.0
                  95       B3016    BLR         3   III    1200.0
                  95       B3017    BLR         3   III    1200.0
                  95       B3018    BLR         3   III    1200.0
                  95       B3019    BLR         3   III    1200.0
                  95       B3020    BLR         3   III    1200.0
                  95       B3021    BLR         3   III    1200.0
                  95       B3022    BLR         3   III    1200.0
                  95       B3023    BLR         3   III    1200.0
                  95       B3024    BLR         3   III    1200.0
                  95       B3025    BLR         3   III    1200.0
                  95       B3026    BLR         3   III    1200.0
2009-01-03 BW08   105      B3118    BLR         3    IV    1200.0
                  105      B3119    BLR         3    IV    1200.0
                  105      B3120    BLR         3    IV    1200.0
                  105      B3121    BLR         3    IV    1200.0
                  105      B3122    BLR         3    IV    1200.0
                  105      B3123    BLR         3    IV    1200.0
                  105      B3124    BLR         3    IV    1200.0
                  105      B3125    BLR         3    IV    1200.0
                  105      B3126    BLR         3    IV    1200.0

                                        Horse  Age              Jockey  \
Date       Season Race No
2008-11-08 BW08   14             MOVIE QUEEN     4             J W D L
                  14       SEASONS GREETINGS     5          K RAJA RAO
                  14           SCENIC MELODY     3           B PRAKASH
                  14        IMPERIAL APPLAUSE    3         B SREEKANTH
2008-12-05 BW08   55           NEEDOFTHEHOUR     4    SAMUEL HITCHCOTT
                  55            GAME OF LIFE     4             T RAHUL
                  55             DOCK OF BAY     4           M NARREDU
                  55              AUCHINLECH     5         S A DESOUSA
                  55             SUPER SONIC     4          C KRISHNAN
                  55              DARK HORSE     5         P S CHOUHAN
                  55             BORN BEAUTY     4          K RAJA RAO
                  55         SMART N SPECIAL     4       A ASHOK KUMAR
                  55              SATIN WOOD     5     G Y RAJESH BABU
                  55               SHE'S BIG     5  M J GAUTAM RAJ URS
                  55                ENFORCER     4               VIVEK
                  55          AN EQUAL MUSIC     4      SAMUEL FARGEAT
2008-12-26 BW08   80                   ZAIOS     5         B SREEKANTH
                  80         BROTHERS IN ARMS    5      SAMUEL FARGEAT
                  80                 DARKTAN     6       A ASHOK KUMAR
                  80         WORTH A MILLION     6  M J GAUTAM RAJ URS
                  80              GARA FLUID     5          K P G APPU
                  80                 DAMGOOD     5        SHOBHAN BABU
                  80           SPANISH CROWN     5        SHANTH KUMAR
                  80         BLACK SPLENDOUR     5        GAURAV SAPRA
                  80                KANDIATE     6     G Y RAJESH BABU
                  80          SPLENDID GLORY     5              R KOCH
                  80       MASTER STRATEGIST     5    SAMUEL HITCHCOTT
                  80         CARIBBEAN PIRATE    5             T RAHUL
2009-01-02 BW08   92              CUTE STYLE     4          AFSAR KHAN
                  92              EXPRESS IT     4              S JOHN
                  92            SULTAN MIRZA     4       A ASHOK KUMAR
                  92                  SABARI     4          C KRISHNAN
                  92            FANTASY KNOT     4        SHOBHAN BABU
                  92          WIN PRETTYBABY     5         DAVID ALLAN
                  92        REIGNING MONARCH     4        VINOD SHINDE
                  92            FLY FOR SURE     4        SHANTH KUMAR
                  92                   AHIRA     4       S SHIVA KUMAR
                  92       DIFFERENT OPINION     4          K CHETHANA
                  92             UNIQUE STAR     4           MD SHAFIQ
                  95            FOREVER MARK     4           B PRAKASH
                  95       CALMING INFLUENCE     4        SALEEM GOLAM
                  95              SPICY STAR     4      SAMUEL FARGEAT
                  95           LUMINOUS GOLD     4           M NARREDU
                  95       VALID EXPECTATION     4              S JOHN
                  95            PANCHAKSHARI     6         B SREEKANTH
                  95              MAN UNITED     4       A ASHOK KUMAR
                  95        LITTLE SPLENDOUR     4       KHURSHAD ALAM
                  95          POWER TO FIGHT     4           MD SHAFIQ
                  95            YOUR DESTINY     4  M J GAUTAM RAJ URS
                  95               SHOWHORSE     5     S CHANDRASHEKAR
                  95                 REPIQUE     4          K P G APPU
2009-01-03 BW08   105        BLACK SPLENDOUR     6       S SHIVA KUMAR
                  105               IMMORTAL     5          C KRISHNAN
                  105      SEASONS GREETINGS     6        SHANTH KUMAR
                  105                ALYCIAA     5       A ASHOK KUMAR
                  105        HAWAIIAN SUNRISE    7              S JOHN
                  105         SAVANNAH PRIDE     5           MD SHAFIQ
                  105             LOOK ALIKE     7     MOHAMMED SHOAIB
                  105         GIRL NEXT DOOR     6       S MALLIKARJUN
                  105         MISS MARVELOUS     5             T RAHUL

                                     Trainer    Wt  Dr Sh  Result    LBW  \
Date       Season Race No
2008-11-08 BW08   14              B PUTTANNA  60.0   8  A       9  11.50
                  14                 B SHIVA  55.5   6  S      10  12.00
                  14             S GANAPATHY  57.0   4  A      11  13.75
                  14              V LOKANATH  54.5   9  S      12  22.25
2008-12-05 BW08   55              AMIT CADDY  56.0  11  A       1   0.00
                  55              M P MAHESH  59.0   1  S       2   1.75
                  55           IRFAN GHATALA  59.0  10  A       3   3.50
                  55            MAHMOOD KHAN  55.0   3  A       4   3.50
                  55              B PUTTANNA  55.0   9  S       5   4.25
                  55         PRADEEP ANNAIAH  54.5  12  S       6   4.25
                  55              V LOKANATH  55.5   6  S       7   6.00
                  55             SAMAR SINGH  55.5   7  S       8   7.00
                  55               S DOMINIC  54.0   5  S       9   8.25
                  55            WARREN SINGH  55.0   8  S      10  11.50
                  55           S INAYATHULLA  51.5   4  S      11  12.25
                  55            FARAZ ARSHAD  61.5   2  A      12  12.25
2008-12-26 BW08   80              V LOKANATH  55.5   5  A       1   0.00
                  80           NEIL DARASHAH  56.0  11  A       2   3.50
                  80              V LOKANATH  60.5   1  A       3   5.00
                  80            WARREN SINGH  57.5   2  S       4   6.75
                  80            MAHMOOD KHAN  56.5  12  S       5   8.25
                  80           S INAYATHULLA  61.5   8  S       6   8.25
                  80                 B SHIVA  52.5   6  S       7   8.25
                  80             SAMAR SINGH  58.5   7  S       8   8.75
                  80                S BRITTO  56.0   3  S       9   9.50
                  80               S NARREDU  52.5   9  A      10   9.50
                  80              AMIT CADDY  61.5  10  S      11  12.25
                  80             G NITYANAND  59.0   4  S      12  14.00
2009-01-02 BW08   92            SHARAT KUMAR  57.5   3  S       1   0.00
                  92                       -  54.0   6  A       2   1.50
                  92                       -  56.5  10  A       3   3.50
                  92              B PUTTANNA  52.5   1  S       4   4.00
                  92           S INAYATHULLA  54.0  11  S       5   5.50
                  92           S PADMANABHAN  59.0   2  A       6   6.50
                  92             S GANAPATHY  52.0   7  S       7   7.25
                  92             R V MANOHAR  57.5   5  S       8   7.75
                  92           IRFAN GHATALA  60.5   9  A       9   0.00
                  92               S NARREDU  60.0   9  A      10  11.25
                  92             R R BYRAMJI  54.0   8  S      11  11.25
                  95             S GANAPATHY  55.0   6  S       1   0.00
                  95          DARIUS BYRAMJI  58.5   1  A       2   0.75
                  95           NEIL DARASHAH  58.5  12  A       3   3.75
                  95               S NARREDU  59.0  10  A       4   4.50
                  95       ARJUN MANGALORKAR  60.5   3  S       5   0.00
                  95            B PRITHVIRAJ  58.5   4  S       6   7.25
                  95              B PUTTANNA  56.5   2  A       7   7.25
                  95             SAMAR SINGH  56.5  11  S       8   8.75
                  95             R V MANOHAR  52.5   7  S       9   8.75
                  95            WARREN SINGH  54.0   9  S      10  10.50
                  95            SHARAT KUMAR  56.5   5  S      11  10.50
                  95            FARAZ ARSHAD  57.5   8  A      12  13.25
2009-01-03 BW08   105           F SIRAJUDDIN  57.0   4  S       1   0.00
                  105             B PUTTANNA  54.0   8  S       2   1.75
                  105                B SHIVA  60.5   1  S       3   2.50
                  105          S INAYATHULLA  61.0  12  S       4   4.00
                  105      ARJUN MANGALORKAR  61.0   9  S       5   6.00
                  105         S S ATTAOLLAHI  52.0   6  S       6   7.00
                  105           B PRITHVIRAJ  62.0  11  S       7   0.00
                  105            R R BYRAMJI  55.5   5  S       8   8.50
                  105            G NITYANAND  60.5   7  A       9  10.50

                           Sr #  Rtg  Penalty  Time in S  Odds  RunNo.  \
Date       Season Race No
2008-11-08 BW08   14       2184    0        0          0     0      -1
                  14       2185    0        0          0     0      -1
                  14       2186    0        0          0     0      -1
                  14       2187    0        0          0     0      -1
2008-12-05 BW08   55       2601    0        0          0     0      -1
                  55       2602    0        0          0     0      -1
                  55       2603    0        0          0     0      -1
                  55       2604    0        0          0     0      -1
                  55       2605    0        0          0     0      -1
                  55       2606    0        0          0     0      -1
                  55       2607    0        0          0     0      -1
                  55       2608    0        0          0     0      -1
                  55       2609    0        0          0     0      -1
                  55       2610    0        0          0     0      -1
                  55       2611    0        0          0     0      -1
                  55       2612    0        0          0     0      -1
2008-12-26 BW08   80       2847    0        0          0     0      -1
                  80       2848    0        0          0     0      -1
                  80       2849    0        0          0     0      -1
                  80       2850    0        0          0     0      -1
                  80       2851    0        0          0     0      -1
                  80       2852    0        0          0     0      -1
                  80       2853    0        0          0     0      -1
                  80       2854    0        0          0     0      -1
                  80       2855    0        0          0     0      -1
                  80       2856    0        0          0     0      -1
                  80       2857    0        0          0     0      -1
                  80       2858    0        0          0     0      -1
2009-01-02 BW08   92       2985    0        0          0     0      -1
                  92       2986    0        0          0     0      -1
                  92       2987    0        0          0     0      -1
                  92       2988    0        0          0     0      -1
                  92       2989    0        0          0     0      -1
                  92       2990    0        0          0     0      -1
                  92       2991    0        0          0     0      -1
                  92       2992    0        0          0     0      -1
                  92       2993    0        0          0     0      -1
                  92       2994    0        0          0     0      -1
                  92       2995    0        0          0     0      -1
                  95       3015    0        0          0     0      -1
                  95       3016    0        0          0     0      -1
                  95       3017    0        0          0     0      -1
                  95       3018    0        0          0     0      -1
                  95       3019    0        0          0     0      -1
                  95       3020    0        0          0     0      -1
                  95       3021    0        0          0     0      -1
                  95       3022    0        0          0     0      -1
                  95       3023    0        0          0     0      -1
                  95       3024    0        0          0     0      -1
                  95       3025    0        0          0     0      -1
                  95       3026    0        0          0     0      -1
2009-01-03 BW08   105      3118    0        0          0     0      -1
                  105      3119    0        0          0     0      -1
                  105      3120    0        0          0     0      -1
                  105      3121    0        0          0     0      -1
                  105      3122    0        0          0     0      -1
                  105      3123    0        0          0     0      -1
                  105      3124    0        0          0     0      -1
                  105      3125    0        0          0     0      -1
                  105      3126    0        0          0     0      -1

                          Venue Name
Date       Season Race No
2008-11-08 BW08   14             BLR
                  14             BLR
                  14             BLR
                  14             BLR
2008-12-05 BW08   55             BLR
                  55             BLR
                  55             BLR
                  55             BLR
                  55             BLR
                  55             BLR
                  55             BLR
                  55             BLR
                  55             BLR
                  55             BLR
                  55             BLR
                  55             BLR
2008-12-26 BW08   80             BLR
                  80             BLR
                  80             BLR
                  80             BLR
                  80             BLR
                  80             BLR
                  80             BLR
                  80             BLR
                  80             BLR
                  80             BLR
                  80             BLR
                  80             BLR
2009-01-02 BW08   92             BLR
                  92             BLR
                  92             BLR
                  92             BLR
                  92             BLR
                  92             BLR
                  92             BLR
                  92             BLR
                  92             BLR
                  92             BLR
                  92             BLR
                  95             BLR
                  95             BLR
                  95             BLR
                  95             BLR
                  95             BLR
                  95             BLR
                  95             BLR
                  95             BLR
                  95             BLR
                  95             BLR
                  95             BLR
                  95             BLR
2009-01-03 BW08   105            BLR
                  105            BLR
                  105            BLR
                  105            BLR
                  105            BLR
                  105            BLR
                  105            BLR
                  105            BLR
                  105            BLR

In [13]:
for i in qualified_horses['Sr #']:
    df.loc[i-1,'RunNo.'] = 0

In [29]:
races_Q_horses = pd.merge(qualified_horses[['Horse']], df, on=["Horse"]).drop_duplicates()
# races_Q_horses.drop(columns=['LBW2', 'combined_data'], inplace=True)
# new.set_index(['Horse', 'Sr #'], inplace=True)
races_Q_horses.head(50)

,Horse,C-Sr#,Date,Season,Centre,Venue ID,Class,Distance,Race No,Age,Jockey,Trainer,Wt,Dr,Sh,Result,LBW,Sr #,Rtg,Penalty,Time in S,Odds,RunNo.,Venue Name
0,ADORABELLA,B178,2008-05-18,BS08,BLR,3,III,1200.0,17,4,D GNANESHWAR,NEIL DARASHAH,60.0,4,A,4,10.25,178,0,0,0,0,-1,BLR
1,ADORABELLA,B481,2008-06-07,BS08,BLR,3,III,1200.0,52,4,D GNANESHWAR,NEIL DARASHAH,57.5,7,A,2,0.50,481,0,0,0,0,-1,BLR
2,ADORABELLA,B1493,2008-07-19,BS08,BLR,3,III,1200.0,152,4,D GNANESHWAR,NEIL DARASHAH,60.0,10,A,7,3.75,1493,0,0,0,0,0,BLR
3,ADORABELLA,B2219,2008-11-15,BW08,BLR,3,III,1200.0,18,4,SAMUEL FARGEAT,NEIL DARASHAH,60.0,1,A,1,0.00,2219,0,0,0,0,-1,BLR
4,ADORABELLA,B6699,2009-08-06,BS09,BLR,3,II,1200.0,201,5,A VELU,NEIL DARASHAH,57.5,1,S,11,27.75,6699,0,0,0,0,-1,BLR
5,ADORABELLA,My4718,2009-08-20,MyR09,MYS,8,II,1200.0,3,5,VIJAY KUMAR,NEIL DARASHAH,58.0,4,S,8,14.25,168051,0,0,0,0,-1,MYS
6,ADORABELLA,My5539,2009-09-18,MyR09,MYS,8,II 5y&o,1200.0,12,5,D GNANESHWAR,NEIL DARASHAH,56.5,2,A,0,100.00,168872,0,0,0,0,-1,MYS
7,STAR SPEED,B2177,2008-11-08,BW08,BLR,3,III,1200.0,14,3,K P G APPU,S PADMANABHAN,58.0,11,A,2,3.75,2177,0,0,0,0,0,BLR
8,DOCK OF BAY,B176,2008-05-18,BS08,BLR,3,III,1200.0,17,4,VINOD SHINDE,IRFAN GHATALA,55.5,2,A,2,2.25,176,0,0,0,0,-1,BLR
9,DOCK OF BAY,B454,2008-06-07,BS08,BLR,3,III,1200.0,49,4,VINOD SHINDE,IRFAN GHATALA,58.5,10,A,9,13.75,454,0,0,0,0,-1,BLR
10,DOCK OF BAY,B2220,2008-11-15,BW08,BLR,3,III,1200.0,18,4,VINOD SHINDE,IRFAN GHATALA,58.0,8,A,2,1.50,2220,0,0,0,0,-1,BLR
11,DOCK OF BAY,B2603,2008-12-05,BW08,BLR,3,III,1200.0,55,4,M NARREDU,IRFAN GHATALA,59.0,10,A,3,3.50,2603,0,0,0,0,0,BLR
12,DOCK OF BAY,B2950,2008-12-27,BW08,BLR,3,III,1200.0,88,4,SAMUEL HITCHCOTT,AMIT CADDY,59.0,6,A,12,19.75,2950,0,0,0,0,-1,BLR
13,BROTHERS IN ARMS,B2297,2008-11-21,BW08,BLR,3,IV,1200.0,25,5,A VELU,NEIL DARASHAH,58.5,1,S,3,5.50,2297,0,0,0,0,-1,BLR
14,BROTHERS IN ARMS,B2769,2008-12-13,BW08,BLR,3,IV,1200.0,72,5,A ASHOK KUMAR,NEIL DARASHAH,56.0,8,S,3,10.25,2769,0,0,0,0,-1,BLR
15,BROTHERS IN ARMS,B2848,2008-12-26,BW08,BLR,3,IV,1200.0,80,5,SAMUEL FARGEAT,NEIL DARASHAH,56.0,11,A,2,3.50,2848,0,0,0,0,0,BLR
16,BROTHERS IN ARMS,B3773,2009-02-14,BW08,BLR,3,IV,1200.0,165,6,SALEEM GOLAM,NEIL DARASHAH,56.5,3,A,1,0.00,3773,0,0,0,0,-1,BLR
17,BROTHERS IN ARMS,B4741,2009-05-17,BS09,BLR,3,IV,1200.0,11,6,D GNANESHWAR,NEIL DARASHAH,61.5,4,A,1,0.00,4741,0,0,0,0,-1,BLR
18,BROTHERS IN ARMS,My4572,2009-08-13,MyR09,MYS,8,III 5y&o,1200.0,1,6,VIJAY KUMAR,NEIL DARASHAH,58.5,5,S,2,1.00,167905,0,0,0,0,-1,MYS
19,SULTAN MIRZA,B1463,2008-07-19,BS08,BLR,3,IV,1200.0,149,3,M NARREDU,-,55.0,5,A,4,3.00,1463,0,0,0,0,-1,BLR
20,SULTAN MIRZA,B2987,2009-01-02,BW08,BLR,3,IV,1200.0,92,4,A ASHOK KUMAR,-,56.5,10,A,3,3.50,2987,0,0,0,0,0,BLR
21,SPICY STAR,B2375,2008-11-22,BW08,BLR,3,IV,1200.0,33,3,SAMUEL FARGEAT,NEIL DARASHAH,60.0,1,A,1,0.00,2375,0,0,0,0,-1,BLR
22,SPICY STAR,B3017,2009-01-02,BW08,BLR,3,III,1200.0,95,4,SAMUEL FARGEAT,NEIL DARASHAH,58.5,12,A,3,3.75,3017,0,0,0,0,0,BLR
23,SPICY STAR,B3827,2009-02-20,BW08,BLR,3,III,1200.0,170,4,S A DESOUSA,NEIL DARASHAH,58.5,3,A,3,4.50,3827,0,0,0,0,-1,BLR
24,SPICY STAR,B4809,2009-05-17,BS09,BLR,3,III,1200.0,16,4,D GNANESHWAR,NEIL DARASHAH,58.0,7,A,8,9.25,4809,0,0,0,0,-1,BLR
25,SPICY STAR,B5153,2009-06-06,BS09,BLR,3,III,1200.0,49,4,SURAJ NARREDU,NEIL DARASHAH,60.0,2,A,7,11.75,5153,0,0,0,0,-1,BLR
26,SPICY STAR,B6632,2009-08-06,BS09,BLR,3,III,1200.0,195,4,A VELU,NEIL DARASHAH,56.0,11,S,11,14.25,6632,0,0,0,0,-1,BLR
27,SPICY STAR,B7071,2009-11-14,BW09,BLR,3,III,1200.0,26,4,P S CHOUHAN,NEIL DARASHAH,58.0,6,S,5,8.50,7071,0,0,0,0,-1,BLR
28,SPICY STAR,B7396,2009-12-04,BW09,BLR,3,III,1200.0,57,4,D GNANESHWAR,NEIL DARASHAH,56.5,8,S,7,12.75,7396,0,0,0,0,-1,BLR
29,SPICY STAR,B7790,2009-12-25,BW09,BLR,3,III,1200.0,96,4,GAURAV SAPRA,NEIL DARASHAH,54.0,11,S,9,9.25,7790,0,0,0,0,-1,BLR
30,SPICY STAR,B8199,2010-01-16,BW09,BLR,3,III,1200.0,137,5,B SREEKANTH,NEIL DARASHAH,53.0,2,S,10,9.00,8199,0,0,0,0,-1,BLR
31,SPICY STAR,B8889,2010-02-26,BW09,BLR,3,IV,1200.0,206,5,J H CHRISTOPHER,NEIL DARASHAH,62.5,11,S,2,5.25,8889,0,0,0,0,-1,BLR
32,SPICY STAR,B13317,2011-02-03,BW10,BLR,3,IV,1200.0,176,6,S JOHN,J BABU RAO,61.5,11,A,1,0.00,13317,0,0,0,0,-1,BLR
33,SPICY STAR,B16967,2011-11-18,BW11,BLR,3,II,1200.0,29,6,VINOD SHINDE,R V MANOHAR,50.0,5,S,8,18.25,16967,0,0,0,0,-1,BLR
34,SPICY STAR,My1965,2008-09-18,MyR08,MYS,8,IV,1200.0,10,3,A VELU,NEIL DARASHAH,58.0,1,S,2,3.25,165298,0,0,0,0,-1,MYS
35,SPICY STAR,My2286,2008-10-03,MyR08,MYS,8,3y,1200.0,14,3,A VELU,NEIL DARASHAH,56.0,12,S,6,8.00,165619,0,0,0,0,-1,MYS
36,SPICY STAR,My5558,2009-09-18,MyR09,MYS,8,III,1200.0,12,4,D GNANESHWAR,NEIL DARASHAH,54.0,11,S,7,4.00,168891,0,0,0,0,0,MYS
37,SPICY STAR,My5882,2009-10-01,MyR09,MYS,8,III 4y&o,1200.0,16,4,V R JAGADEESH,NEIL DARASHAH,53.0,2,S,2,1.00,169215,0,0,0,0,-1,MYS
38,SPICY STAR,My15240,2011-10-26,MyR11,MYS,8,III 5y&o,1200.0,18,6,B SREEKANTH,R V MANOHAR,60.0,2,S,10,19.50,178573,0,0,0,0,-1,MYS
39,SPICY STAR,My19493,2012-10-21,MyR12,MYS,8,III 5y&o,1200.0,18,7,NASSAR ALAM,S SANTOSH RAO,60.0,2,S,11,22.75,182826,0,0,0,0,-1,MYS
40,SPICY STAR,My19741,2012-11-14,MyW12,MYS,8,III,1200.0,2,7,AFSAR KHAN,S SANTOSH RAO,59.0,1,S,8,9.50,183074,0,0,0,0,-1,MYS
41,SPICY STAR,My19993,2012-12-05,MyW12,MYS,8,III,1200.0,5,7,AFSAR KHAN,S SANTOSH RAO,58.0,7,S,11,19.00,183326,0,0,0,0,-1,MYS
42,SPICY STAR,My20195,2012-12-19,MyW12,MYS,8,III 4y&o,1200.0,7,7,AFSAR KHAN,S SANTOSH RAO,58.0,4,S,9,13.75,183528,0,0,0,0,-1,MYS
65,ALYCIAA,B1663,2008-07-26,BS08,BLR,3,IV,1200.0,169,4,VIVEK,S INAYATHULLA,56.5,8,S,8,20.00,1663,0,0,0,0,-1,BLR
66,ALYCIAA,B1998,2008-08-08,BS08,BLR,3,IV,1200.0,205,4,VIVEK,S INAYATHULLA,56.5,10,S,9,21.00,1998,0,0,0,0,-1,BLR
67,ALYCIAA,B2349,2008-11-21,BW08,BLR,3,IV,1200.0,30,4,A ASHOK KUMAR,S INAYATHULLA,61.0,5,S,4,3.75,2349,0,0,0,0,-1,BLR
68,ALYCIAA,B3121,2009-01-03,BW08,BLR,3,IV,1200.0,105,5,A ASHOK KUMAR,S INAYATHULLA,61.0,12,S,4,4.00,3121,0,0,0,0,0,BLR
69,ALYCIAA,B3421,2009-01-23,BW08,BLR,3,IV,1200.0,132,5,S SHIVA KUMAR,S INAYATHULLA,60.5,1,S,6,0.00,3421,0,0,0,0,-1,BLR
70,MARCEGALIA,B260,2008-05-25,BS08,BLR,3,3y,1200.0,25,3,L MARSHALL,J S DHARIWAL,56.0,2,A,1,0.00,260,0,0,0,0,-1,BLR
71,MARCEGALIA,B921,2008-06-22,BS08,BLR,3,III,1200.0,95,3,SURAJ NARREDU,J S DHARIWAL,55.0,3,A,3,1.25,921,0,0,0,0,-1,BLR

In [11]:
zerothindex = races_Q_horses.index[races_Q_horses['RunNo.'] == 0].tolist()
removed_horses = []
print(zerothindex)
for i in zerothindex:
    if (i+1 in races_Q_horses.index):
#         if (races_Q_horses.loc[i+1, 'Horse'] == races_Q_horses.loc[i, 'Horse'] and races_Q_horses.loc[i+1, 'Dr']<10):
#             races_Q_horses.loc[i+1, 'RunNo.'] = 1
#         elif (races_Q_horses.loc[i+1, 'Horse'] == races_Q_horses.loc[i, 'Horse'] and races_Q_horses.loc[i+1, 'Dr']>=10):
#             removed_horses.append(races_Q_horses.loc[i, 'Horse'])
#             races_Q_horses = races_Q_horses.loc[races_Q_horses['Horse'] != races_Q_horses.loc[i, 'Horse']]
        if (races_Q_horses.loc[i+1, 'Horse'] == races_Q_horses.loc[i, 'Horse']):
            races_Q_horses.loc[i+1, 'RunNo.'] = 1

[2, 7, 11, 15, 20, 22, 36, 44, 58, 68, 73, 95, 104, 123, 133, 137, 152, 158, 162, 170, 191, 202, 223, 283, 321, 332, 350, 372, 408, 423, 435, 459, 481, 506, 514, 518, 522, 531, 546, 555, 580, 594, 611, 619, 630, 641, 668, 679, 710, 734, 743, 751, 770, 798, 834, 841, 854, 861, 862, 876, 879, 885, 887, 897, 899, 908, 920, 938, 980, 993, 1002, 1032, 1041, 1065, 1070, 1091, 1114, 1125, 1156, 1211, 1216, 1252, 1257, 1288, 1329, 1350, 1387, 1423, 1435, 1461, 1497, 1530, 1536, 1544, 1553, 1561, 1582, 1614, 1622, 1633, 1648, 1675, 1687, 1714, 1721, 1725, 1730, 1734, 1739, 1752, 1756, 1761, 1765, 1770, 1773, 1783, 1810, 1814, 1826, 1830, 1843, 1858, 1880, 1892, 1912, 1915, 1926, 1929, 1942, 1964, 1986, 1991, 2004, 2006, 2011, 2016, 2020, 2025, 2032, 2036, 2059, 2063, 2080, 2088, 2104, 2115, 2121, 2132, 2144, 2156, 2165, 2170, 2176, 2192, 2205, 2211, 2222, 2227, 2238, 2250, 2253, 2255, 2272, 2275, 2277, 2294, 2297, 2299, 2311, 2350, 2360, 2373, 2381, 2384, 2405, 2422, 2455, 2468, 2472, 2495, 2532, 2542, 2561, 2597, 2606, 2610, 2614, 2618, 2642, 2651, 2675, 2684, 2687, 2709, 2721, 2730, 2735, 2739, 2751, 2770, 2787, 2793, 2807, 2809, 2811, 2816, 2818, 2824, 2837, 2845, 2849, 2853, 2861, 2872, 2882, 2893, 2894, 2906, 2907, 2914, 2939, 2944, 2956, 2959, 2961, 2968, 2973, 2978, 2985, 2993, 3003, 3013, 3029, 3032, 3033, 3037, 3050, 3053, 3060, 3067, 3069, 3073, 3074, 3077, 3088, 3093, 3094, 3098, 3107, 3112, 3120, 3131, 3140, 3152, 3162, 3169, 3175, 3184, 3188, 3193, 3195, 3197, 3200, 3202, 3206, 3219, 3227, 3248, 3252, 3273, 3274, 3280, 3285, 3293, 3298, 3304, 3313, 3322, 3332, 3340, 3352, 3356, 3358, 3362, 3368, 3376, 3377, 3379, 3381, 3387, 3390, 3393, 3394, 3397, 3402, 3408, 3417, 3421, 3433, 3441, 3445, 3451, 3453, 3459, 3462, 3464, 3471, 3474, 3487, 3490, 3504, 3509, 3517, 3529, 3536, 3544, 3557, 3567, 3573, 3581, 3582, 3588, 3589, 3591, 3595, 3598, 3612, 3620, 3635, 3655, 3669, 3677, 3683, 3693, 3700, 3727, 3731, 3734, 3752, 3764, 3776, 3795, 3804, 3834, 3839, 3852, 3863, 3865, 3867, 3871, 3874, 3877, 3892, 3904, 3910, 3919, 3927, 3938, 3943, 3954, 3979, 3982, 3989, 3998, 4007, 4015, 4022, 4033, 4042, 4051, 4066, 4081, 4096, 4103, 4104, 4120, 4125, 4134, 4145, 4157, 4159, 4162, 4166, 4168, 4175, 4184, 4191, 4199, 4214, 4216, 4222, 4226, 4241, 4249, 4255, 4266, 4272, 4287, 4302, 4322, 4331, 4334, 4337, 4349, 4352, 4367, 4377, 4387, 4396, 4402, 4403, 4405, 4406, 4407, 4408, 4410, 4414, 4417, 4421, 4431, 4438, 4444, 4448, 4450, 4465, 4473, 4479, 4493, 4505, 4520, 4528, 4538, 4551, 4557, 4560, 4567, 4574, 4591, 4599, 4606, 4617, 4621, 4632, 4639, 4650, 4663, 4675, 4678, 4685, 4711, 4716, 4730, 4734, 4745, 4763, 4788, 4796, 4800, 4803, 4822, 4832, 4842, 4861, 4869, 4872, 4876, 4892, 4900, 4904, 4912, 4922, 4924, 4933, 4943, 4950, 4964, 4980, 4989, 5002, 5013, 5015, 5026, 5033, 5040, 5046, 5050, 5052, 5056, 5058, 5062, 5067, 5070, 5077, 5083, 5089, 5093, 5096, 5101, 5106, 5111, 5112, 5118, 5129, 5132, 5143, 5156, 5167, 5168, 5175, 5176, 5184, 5185, 5192, 5201, 5206, 5211, 5217, 5222, 5223, 5234, 5243, 5247, 5249, 5259, 5270, 5285, 5297, 5310, 5326, 5328, 5337, 5339, 5344, 5361, 5373, 5400, 5401, 5409, 5423, 5424, 5432, 5446, 5447, 5455, 5469, 5490, 5503, 5524, 5555, 5571, 5599, 5657, 5696, 5705, 5719, 5734, 5748, 5762, 5777, 5801, 5810, 5822, 5849, 5866, 5887, 5903, 5919, 5928, 5959, 5984, 5997, 6036, 6079, 6090, 6096, 6109, 6127, 6135, 6164, 6172, 6184, 6200, 6203, 6225, 6228, 6252, 6265, 6295, 6302, 6336, 6358, 6364, 6369, 6395, 6396, 6422, 6423, 6443, 6446, 6474, 6489, 6498, 6508, 6525, 6539, 6548, 6564, 6590, 6602, 6619, 6625, 6637, 6643, 6703, 6729, 6736, 6749, 6762, 6786, 6787, 6790, 6797, 6800, 6819, 6839, 6845, 6853, 6861, 6864, 6869, 6874, 6877, 6881, 6887, 6892, 6895, 6898, 6915, 6928, 6953, 6965, 6986, 7010, 7025, 7028, 7030, 7033, 7043, 7051, 7067, 7075, 7085, 7097, 7138, 7147, 7153, 7166, 7172, 7185, 7191, 7197, 7221, 7233, 7251, 7259, 7271, 7279, 7280, 7281, 7294, 7298, 7309, 7316, 7319, 7335, 7338, 7365, 7369, 7374, 7380, 7382, 7390, 7396, 7401, 7415, 7441, 7454, 7464, 7485, 7488, 7489, 7495, 7496, 7520, 7532, 7542, 7551, 7567, 7587, 7619, 7635, 7659, 7671, 7687, 7705, 7716, 7723, 7729, 7732, 7736, 7755, 7782, 7791, 7803, 7808, 7817, 7821, 7832, 7838, 7851, 7863, 7877, 7881, 7896, 7900, 7913, 7921, 7927, 7935, 7946, 7954, 7968, 7985, 7990, 8015, 8026, 8035, 8042, 8053, 8074, 8081, 8094, 8102, 8108, 8129, 8147, 8154, 8174, 8184, 8201, 8217, 8227, 8238, 8243, 8250, 8258, 8271, 8277, 8281, 8299, 8306, 8316, 8321, 8327, 8353, 8362, 8364, 8368, 8380, 8384, 8385, 8390, 8398, 8403, 8407, 8413, 8415, 8422, 8425, 8428, 8442, 8455, 8458, 8460, 8463, 8475, 8479, 8485, 8486, 8493, 8501, 8510, 8518, 8519]

In [12]:
TrackedRuns = races_Q_horses.loc[races_Q_horses['RunNo.']>=0]
# TrackedRuns.set_index(['Horse', 'Sr #'], inplace = True)
TrackedRuns

,Horse,C-Sr#,Date,Season,Centre,Venue ID,Class,Distance,Race No,Age,Jockey,Trainer,Wt,Dr,Sh,Result,LBW,Sr #,Rtg,Penalty,Time in S,Odds,RunNo.,Venue Name
2,ADORABELLA,B1493,2008-07-19,BS08,BLR,3,III,1200.0,152,4,D GNANESHWAR,NEIL DARASHAH,60.0,10,A,7,3.75,1493,0,0,0,0,0,BLR
3,ADORABELLA,B2219,2008-11-15,BW08,BLR,3,III,1200.0,18,4,SAMUEL FARGEAT,NEIL DARASHAH,60.0,1,A,1,0.00,2219,0,0,0,0,1,BLR
7,STAR SPEED,B2177,2008-11-08,BW08,BLR,3,III,1200.0,14,3,K P G APPU,S PADMANABHAN,58.0,11,A,2,3.75,2177,0,0,0,0,0,BLR
11,DOCK OF BAY,B2603,2008-12-05,BW08,BLR,3,III,1200.0,55,4,M NARREDU,IRFAN GHATALA,59.0,10,A,3,3.50,2603,0,0,0,0,0,BLR
12,DOCK OF BAY,B2950,2008-12-27,BW08,BLR,3,III,1200.0,88,4,SAMUEL HITCHCOTT,AMIT CADDY,59.0,6,A,12,19.75,2950,0,0,0,0,1,BLR
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8501,THEA'S PET,M28426,2021-01-24,M20,MUM,2,V,1200.0,100,7,P S Kaviraj,Narendra Lagad,56.0,12,A,5,3.50,240555,0,0,0,0,0,MUM
8502,THEA'S PET,M28605,2021-01-29,M20,MUM,2,V 5y&o,1200.0,118,7,P S Kaviraj,Narendra Lagad,55.5,5,A,12,12.50,240734,0,0,0,0,1,MUM
8510,SALTBAE,M28603,2021-01-29,M20,MUM,2,V 5y&o,1200.0,118,5,Shrikant Kamble,Deepesh Narredu,57.5,14,A,2,3.50,240732,0,0,0,0,0,MUM
8518,MONK,M28844,2021-02-28,M20,MUM,2,IV 5y&o,1200.0,144,5,S Zervan,Sanjay Kolse,58.5,10,A,6,4.00,240973,0,0,0,0,0,MUM
8519,RIVER SONG,M29061,2021-03-14,M20,MUM,2,M3y,1200.0,166,3,P Trevor,L D Silva,54.5,12,A,4,4.00,241190,0,0,0,0,0,MUM

In [13]:
to_drop = []
for i in TrackedRuns.loc[TrackedRuns['RunNo.']==1].index:
#     print(i)
    if TrackedRuns.loc[i, 'Dr']>=10:
        to_drop.append(i)
print(len(TrackedRuns))
TrackedRuns.drop(to_drop, inplace=True)
print(len(TrackedRuns))

1449
1320

C:\Users\Testing\anaconda3\lib\site-packages\pandas\core\frame.py:3990: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().drop(

In [14]:
removed_horses

[]

In [15]:
qualified_horse_summary = TrackedRuns.loc[TrackedRuns['RunNo.']==1].reset_index()
qualified_horse_summary = qualified_horse_summary[['Horse', 'Distance', 'Jockey', 'Dr', 'Result']]
qualified_horse_summary.index = np.arange(1, len(qualified_horse_summary) + 1)
qualified_horse_summary

                Horse  Distance            Jockey  Dr  Result
1         ADORABELLA     1200.0    SAMUEL FARGEAT   1       1
2        DOCK OF BAY     1200.0  SAMUEL HITCHCOTT   6      12
3    BROTHERS IN ARMS    1200.0      SALEEM GOLAM   3       1
4         SPICY STAR     1200.0       S A DESOUSA   3       3
5         SPICY STAR     1200.0     V R JAGADEESH   2       2
..                ...       ...               ...  ..     ...
534  ADAMS BEGINNING     1200.0       D R Shubham   9       4
535       SASSY LASS     1200.0         A S Peter   1       2
536           SAFDAR     1200.0     Bhawani Singh   5       4
537          BELENUS     1200.0           P Vinod   6       9
538       THEA'S PET     1200.0       P S Kaviraj   5      12

[538 rows x 5 columns]

In [16]:
qualified_horse_summary['Result'].value_counts()

1     78
3     69
2     68
5     60
4     48
7     44
8     41
6     41
9     39
10    18
11    12
0     10
12     5
13     4
14     1
Name: Result, dtype: int64

In [17]:
df[df['Jockey'].isna()]

Empty DataFrame
Columns: [C-Sr#, Date, Season, Centre, Venue ID, Class, Distance, Race No, Horse, Age, Jockey, Trainer, Wt, Dr, Sh, Result, LBW, Sr #, Rtg, Penalty, Time in S, Odds, RunNo., Venue Name]
Index: []

In [18]:
data['Time in S'].unique()

array([0], dtype=int64)

In [26]:
[x for x in sorted(df['Horse'].unique()) if 'STAR' in x]

['A SHOOTING STAR\xa0',
 'ABSOLUTE STAR\xa0',
 'ACCELERATING STAR',
 'ACE ANGEL STAR\xa0',
 'ACE STAR\xa0',
 "ADAM'S STAR\xa0",
 'AERO STAR\xa0',
 'ALBERTON STAR\xa0',
 'ALL STAR GENERAL ',
 'ALL STAR GENERAL\xa0',
 'ALLSTAR\xa0',
 'ALWAYS A STAR\xa0',
 'ALWAYSASTAR ',
 'AMAZING STAR ',
 'AMBER STAR\xa0',
 'AMBITIOUS STAR ',
 'ANVILL STAR',
 'ANVILL STAR ',
 'ANVILL STAR\xa0',
 'APOLLO STAR\xa0',
 'APRIL STAR\xa0',
 'AQUA STAR ',
 'ARABIAN STAR\xa0',
 'ARISEN STAR\xa0',
 'ARYA STARK\xa0',
 'ASCOT STAR\xa0',
 'ASIAN STAR',
 'ASIAN STAR ',
 'ASIAN STAR\xa0',
 'ASIATIC STAR\xa0',
 'ASPIRING STAR\xa0',
 'ASTARA',
 'ASTARA ',
 'ASTRAL STAR ',
 'ATHLETIC STAR\xa0',
 'ATLANTIC STAR\xa0',
 'ATLAS STAR\xa0',
 'AWESOME STAR\xa0',
 'AZETIC STAR ',
 'AZETIC STAR\xa0',
 'BE A STAR\xa0',
 'BE MY STAR ',
 'BEE THE STAR\xa0',
 'BEYOND STARS\xa0',
 'BIG STAR ',
 'BIRTHDAY STAR\xa0',
 'BLACK SUPER STAR\xa0',
 'BLUE STAR\xa0',
 'BOLD STAR\xa0',
 'BOOKIES STAR\xa0',
 'BOTSWANA STAR ',
 'BRIGHT STAR\xa0',
 'BRIGHTEST STAR\xa0',
 'BURST OF STARDUST\xa0',
 'CAESARS STAR\xa0',
 'CALICO STAR\xa0',
 'CANDESCENT STAR ',
 'CELESTAR',
 'CELESTAR ',
 'CELESTAR\xa0',
 'CHALLENGING STAR ',
 'CHAMPIONS STAR\xa0',
 'CLASSIC STAR\xa0',
 'COLONELS STAR\xa0',
 "COUNTRY'S STAR ",
 'COURAGEOUS STAR ',
 'CROWN OF STARS ',
 'CROWN OF STARS\xa0',
 'DANSTAR\xa0',
 'DAWNSTAR ',
 'DAZZLING STAR ',
 'DAZZLING STAR\xa0',
 'DELTIC STAR\xa0',
 'DIAMOND STAR\xa0',
 'DREAM STAR',
 'DREAM STAR ',
 'DREAM STAR\xa0',
 'EASTERN STAR ',
 'ELEGANT STAR\xa0',
 'ELUSIVE STAR ',
 'EMERALD STAR\xa0',
 'EMERGING STAR ',
 'EMERGING STAR\xa0',
 'ENDURING STAR\xa0',
 'ESTRELLA STAR ',
 'EUROPA STAR ',
 'EUROPEAN STAR ',
 'EXCELLENT STAR ',
 'EXCLUSIVE STAR\xa0',
 'EXQUISITE STAR ',
 'FANTASTIC STAR\xa0',
 'FASHION OF STARS ',
 'FESTIVE STAR ',
 'FIGHTING STAR\xa0',
 'FIRE STAR\xa0',
 'FLAMBOYANT STAR\xa0',
 'FLASH STAR ',
 'FLYING STAR\xa0',
 'FORMIDABLE STAR ',
 'FORTUNE STAR\xa0',
 'FRESH START\xa0',
 'GAGAN STAR ',
 'GAGAN STAR\xa0',
 'GALLANT STAR ',
 'GALLOPING STAR ',
 'GENUINE STAR ',
 'GOLDEN STAR\xa0',
 'GONNA BE A ROKSTAR\xa0',
 'GREEK STAR',
 'GREEK STAR\xa0',
 'HAPTICSTAR',
 'HAPTICSTAR ',
 'HAPTICSTAR\xa0',
 'HIDDEN STAR\xa0',
 'HOT STAR ',
 'HOT STAR\xa0',
 'HURRICANE STAR\xa0',
 'ICELANDIC STAR\xa0',
 'IMPERIAL STAR\xa0',
 'IN THE STARS ',
 'IN THE STARS\xa0',
 'INCREDIBLE STAR ',
 'INDIAN STAR ',
 "JASSI'S STAR\xa0",
 'JEM STAR',
 'JEM STAR\xa0',
 'KALINGA STAR\xa0',
 'KING STAR ',
 'KING STAR\xa0',
 'KISS THE STAR\xa0',
 'KUNIGAL STAR\xa0',
 'LAD STAR\xa0',
 'LADY BLACK STAR\xa0',
 'LAKE STAR\xa0',
 'LIBERTY STAR\xa0',
 'LIKEASTAR',
 'LUCKY GOLD STAR\xa0',
 'LUCKY STAR\xa0',
 'MAGICAL STAR\xa0',
 'MAGNIFICENT STAR ',
 'MAGNITUDE STAR\xa0',
 'MAKE ME A STAR\xa0',
 'MAPLE STAR\xa0',
 'MAXIMUM STAR ',
 'MEGA STAR\xa0',
 'MID SUMMER STAR\xa0',
 'MIDNIGHT STAR ',
 'MIDNIGHT STAR\xa0',
 'MIGHTY STAR ',
 'MISS STARLIGHT\xa0',
 'MOON STAR\xa0',
 'MORNING STAR\xa0',
 'MOVING STAR',
 'MULTISTAR',
 'MULTISTAR ',
 'MULTISTAR\xa0',
 'MY LUCKY STAR\xa0',
 'MY STAR\xa0',
 'MYSTIC STAR ',
 'MYSTICAL STAR\xa0',
 'NATIONAL STAR\xa0',
 'NEW STAR\xa0',
 "NEWS O' STAR",
 "NEWS O' STAR ",
 "NEWS O' STAR\xa0",
 "NEWS O'STAR\xa0",
 'NEXTSTAR ',
 'NEXTSTAR\xa0',
 'NOBLE STAR\xa0',
 'NORTH STAR ',
 'OASIS STAR\xa0',
 'OCEAN STAR\xa0',
 'ORIENTAL STAR\xa0',
 'ORION STAR\xa0',
 'PACIFIC STAR\xa0',
 'PARTY STARTER ',
 'PASSING STAR\xa0',
 'PERFECT STAR ',
 'PHANTOM OF STARS',
 'PHANTOM OF STARS ',
 'POINT THE STAR ',
 'POTENTIAL STAR\xa0',
 'POWER STAR\xa0',
 'POWERFUL STAR ',
 'PRETTY STAR ',
 'PRETTY STAR\xa0',
 'PRIME STAR ',
 'PRIME STAR\xa0',
 'PROUD STAR\xa0',
 'PURPLE STAR\xa0',
 'QUEEN OF THE STARS',
 'QUEEN OF THE STARS\xa0',
 'RACE FOR THE STARS ',
 'RAGING STAR\xa0',
 'REACH THE STARS',
 'REACH THE STARS ',
 'REACH THE STARS\xa0',
 'REBEL STAR\xa0',
 'RENO STAR ',
 'REPUBLICAN STAR\xa0',
 'REVAN STAR ',
 'REVAN STAR\xa0',
 'REWRITE THE STARS ',
 'RIDGEWOOD STAR',
 'RIDGEWOOD STAR ',
 'RIDGEWOOD STAR\xa0',
 'RISING LITTLE STAR',
 'RIVER STAR\xa0',
 'ROCK THE STARS\xa0',
 'ROCKA STAR\xa0',
 'ROHINI STAR\xa0',
 'ROSHAN STAR\xa0',
 'ROYAL BLUE STAR\xa0',
 'RUBIK STAR ',
 'RUNNING STAR\xa0',
 'SALONIKA STAR ',
 'SANDALWOOD STAR',
 'SATSUMA STAR\xa0',
 'SCINTILLATING STAR\xa0',
 'SEA OF STARS',
 'SEA OF STARS\xa0',
 'SEASIDE STAR\xa0',
 'SECRETSUPERSTAR ',
 'SECRETSUPERSTAR\xa0',
 'SEVEN STAR\xa0',
 'SEVENTH STAR ',
 "SHE'S A STAR\xa0",
 'SHIMMERING STAR ',
 'SHINING STAR ',
 'SHINING STAR\xa0',
 'SHIVALIK STAR',
 'SHIVALIK STAR ',
 'SHIVALIK STAR\xa0',
 'SIZZLING STAR\xa0',
 'SKYFULLOFSTARS',
 'SKYFULLOFSTARS ',
 'SKYFULLOFSTARS\xa0',
 'SMART STAR\xa0',
 'SON OF STARS ',
 'SON OF STARS\xa0',
 'SONIC STAR',
 'SONIC STAR ',
 'SONIC STAR\xa0',
 'SOVEREIGN STAR ',
 'SPARKLING STAR\xa0',
 'SPEAKING OF STARS ',
 'SPICY STAR ',
 'SPICY STAR\xa0',
 'SPIRITUAL STAR\xa0',
 'SPORTING STAR\xa0',
 'SPRINT STAR\xa0',
 'STAR AACT ',
 'STAR ABILITY\xa0',
 'STAR ACE ',
 'STAR ACE\xa0',
 'STAR ALONE\xa0',
 'STAR AND GARTER ',
 'STAR AND STRIPES\xa0',
 'STAR ANISE ',
 'STAR ANISE\xa0',
 'STAR APPEARANCE ',
 'STAR ASSEMBLY\xa0',
 'STAR ATRIUM ',
 'STAR ATRIUM\xa0',
 'STAR ATTRACTION\xa0',
 'STAR BABE',
 'STAR BABE ',
 'STAR BARON ',
 'STAR BENEVOLENT\xa0',
 'STAR BINDER',
 'STAR BINDER ',
 'STAR BINDER\xa0',
 'STAR BLAZE\xa0',
 'STAR BLESSINGS\xa0',
 'STAR BLUE\xa0',
 'STAR BRIGADE ',
 'STAR BRIGHT\xa0',
 'STAR BUILDER\xa0',
 'STAR BURST\xa0',
 'STAR CALIBER ',
 'STAR CARNATION ',
 'STAR CARNATION\xa0',
 'STAR CAVALRY ',
 'STAR CAVIAR ',
 'STAR CHIEFTAIN ',
 'STAR CITIZEN ',
 'STAR COMMAND\xa0',
 'STAR COMRADE ',
 'STAR COMRADE\xa0',
 'STAR CONVOY ',
 'STAR CONVOY\xa0',
 'STAR COUNCILLOR ',
 'STAR COUNCILLOR\xa0',
 'STAR CRACKER ',
 'STAR CRACKER\xa0',
 'STAR CRAFT\xa0',
 'STAR CREST\xa0',
 'STAR CRUISE',
 'STAR CRUISE ',
 'STAR DANCER',
 'STAR DANCER ',
 'STAR DIVA ',
 'STAR DREAMS ',
 'STAR DREAMS\xa0',
 'STAR ELEGANCE\xa0',
 'STAR ELEGANT ',
 'STAR EMPIRE\xa0',
 'STAR ENGAGEMENT\xa0',
 'STAR ENVOY ',
 'STAR EXPERIENCE\xa0',
 'STAR FIRE BOY\xa0',
 'STAR FIRE LADY\xa0',
 'STAR FIRE PRINCE ',
 'STAR FLIGHT\xa0',
 'STAR FLING ',
 'STAR FUTURE\xa0',
 'STAR GAZER',
 'STAR GAZER ',
 'STAR GAZER\xa0',
 'STAR GAZING\xa0',
 'STAR GLEAM\xa0',
 'STAR GLITTER ',
 'STAR GLORY\xa0',
 'STAR GLOW\xa0',
 'STAR GODDESS\xa0',
 'STAR GUITAR ',
 'STAR GUNNS ',
 'STAR GUNNS\xa0',
 'STAR HIGHNESS',
 'STAR HIGHNESS\xa0',
 'STAR HOLIDAY ',
 'STAR HOPPER ',
 'STAR IMAGE\xa0',
 'STAR IMPACT\xa0',
 'STAR IMPERIAL ',
 'STAR INSPIRATION\xa0',
 'STAR INVITATION\xa0',
 'STAR IS BORN\xa0',
 'STAR KINGDOM ',
 'STAR KINGDOM\xa0',
 'STAR LADY\xa0',
 'STAR LAGOON ',
 'STAR LAGOON\xa0',
 'STAR LEAGUE\xa0',
 'STAR LEGACY\xa0',
 'STAR LIGHTNING\xa0',
 'STAR LINE\xa0',
 'STAR LORD\xa0',
 'STAR LUXURIOUS\xa0',
 'STAR MAN ',
 'STAR MARQUESS ',
 'STAR MARQUESS\xa0',
 'STAR MIRACLE\xa0',
 'STAR MOUNTAIN\xa0',
 'STAR MUSTANG\xa0',
 'STAR OF BABYLON\xa0',
 'STAR OF CARDIFF\xa0',
 'STAR OF DECCAN\xa0',
 'STAR OF DESIRE\xa0',
 'STAR OF DESTINY ',
 'STAR OF DESTINY\xa0',
 'STAR OF EXCELLENCE\xa0',
 'STAR OF FASHION ',
 'STAR OF GOODWILL ',
 'STAR OF HARMONY\xa0',
 'STAR OF HEARTS\xa0',
 'STAR OF KILLARNEY',
 'STAR OF MANHATTAN\xa0',
 'STAR OF PARADISE\xa0',
 'STAR OF PEACE\xa0',
 'STAR OF ROSES\xa0',
 'STAR OF STARS\xa0',
 'STAR OF THE TRACK',
 'STAR OF THEA ',
 'STAR OF THEA\xa0',
 'STAR OF TIARA ',
 'STAR OF VENUS\xa0',
 'STAR OF ZOLTAN\xa0',
 'STAR ONE',
 'STAR ONE ',
 'STAR ONE\xa0',
 'STAR PHOENIX\xa0',
 'STAR PLAYER',
 'STAR PLAYER\xa0',
 'STAR PORTAL ',
 'STAR PORTAL\xa0',
 'STAR PRESENCE\xa0',
 'STAR PRINCE\xa0',
 'STAR PROOF ',
 'STAR PROSPECT\xa0',
 'STAR RACER ',
 'STAR RANKING ',
 'STAR RANKING\xa0',
 'STAR RISING\xa0',
 'STAR ROUTE ',
 'STAR ROUTE\xa0',
 'STAR ROYLE ',
 'STAR RUBY\xa0',
 'STAR SALONI\xa0',
 'STAR SAPPHIRE ',
 'STAR SCHOLAR',
 'STAR SCHOLAR ',
 'STAR SCHOLAR\xa0',
 'STAR SENSATION\xa0',
 'STAR SHIP\xa0',
 'STAR SILVER ',
 'STAR SINCERITY ',
 'STAR SKIPPER\xa0',
 'STAR SPEED\xa0',
 'STAR STALINGRAD ',
 'STAR STORM\xa0',
 'STAR STRIKER\xa0',
 'STAR STUDDED ',
 'STAR STUDDED\xa0',
 'STAR STYLE ',
 'STAR STYLE\xa0',
 'STAR SUCCESS\xa0',
 'STAR SUPREMO ',
 'STAR SYMPHONY\xa0',
 'STAR TEMPLAR ',
 'STAR TRAINER\xa0',
 'STAR TREASURE\xa0',
 'STAR TWIST ',
 'STAR TWIST\xa0',
 'STAR VALUE\xa0',
 'STAR VISION\xa0',
 'STAR WAGER\xa0',
 'STAR WARRIOR\xa0',
 'STAR WARS\xa0',
 'STAR WAVES ',
 'STAR WAVE\xa0',
 'STAR WINGS\xa0',
 'STAR WISH\xa0',
 'STAR WITNESS',
 'STAR WITNESS ',
 'STAR WITNESS\xa0',
 'STAR ZONE\xa0',
 'STARBOY ',
 'STARDOM BOUND\xa0',
 'STARDOM CALLING',
 'STARDOM CALLING ',
 'STARDOM CALLING\xa0',
 'STARDOM GIRL\xa0',
 'STARFIRE ',
 'STARHUNT',
 'STARHUNT ',
 'STARHUNT\xa0',
 'STARI GRAD ',
 'STARIDAR\xa0',
 'STARISTA\xa0',
 'STARISTOCRAT\xa0',
 'STARKE\xa0',
 'STARLET',
 'STARLET\xa0',
 'STARLIGHT',
 'STARLIGHT ',
 'STARLIGHT MAGIC\xa0',
 'STARLIGHT\xa0',
 'STARR VERDICT\xa0',
 'STARRER\xa0',
 'STARRIANO\xa0',
 'STARRINGO ',
 'STARRING\xa0',
 'STARRY EYES\xa0',
 'STARRY IMAGE',
 'STARRY IMAGE ',
 'STARRY IMAGE\xa0',
 'STARRY MOMENT\xa0',
 'STARRY OCEAN\xa0',
 'STARRY VIEW\xa0',
 'STARRY WIND ',
 'STARRY WIND\xa0',
 'STARS FOR YOU ',
 'STARS IN HIS EYES ',
 'STARSCREAM\xa0',
 'STARSEEKER\xa0',
 'STARSONBOARD\xa0',
 'STARSTRUCK',
 'STARSTRUCK\xa0',
 'STARWALKER ',
 'STARWALT ',
 'STELLAR STAR\xa0',
 'STORM STAR ',
 'STORM STAR\xa0',
 'STRIKE THE STARS\xa0',
 'SUCCEEDING STAR\xa0',
 'SUCCESS STAR\xa0',
 'SUMMER STAR\xa0',
 'SUN MOON AND STARS\xa0',
 'SUPER START\xa0',
 'SUPER STAR\xa0',
 'SUPERSTAR SUPREME\xa0',
 'SWEEPING STAR\xa0',
 'SWIFT STAR\xa0',
 "SYMBOL OF STAR'S",
 "SYMBOL OF STAR'S\xa0",
 'SYMBOLIC STAR ',
 'SYMBOLIC STAR\xa0',
 'TEEN STAR\xa0',
 'TESTAROSA\xa0',
 "THAT'S MY STAR ",
 'THUNDER STAR\xa0',
 'THUNDERING STAR\xa0',
 'TOP STAR ',
 'TOP STARCHY\xa0',
 'TOP STAR\xa0',
 'TRACK STAR ',
 'TRICKY STAR\xa0',
 'TRISTAR ',
 'TRUMP STAR',
 'TRUMP STAR ',
 'TURF STAR ',
 'TURF STAR\xa0',
 'TWINKLING STAR ',
 'UNIQUE STAR\xa0',
 'UNSEEDED STAR\xa0',
 'UPON A STAR\xa0',
 'VALIANT STAR ',
 'VAN DE STAR\xa0',
 "VEENA'S STAR\xa0",
 'VENUS STAR ',
 'VENUS STAR\xa0',
 'WATCHMYSTARS ',
 'WILL STAR ',
 'WILL STAR\xa0',
 'WIMBELDON STAR\xa0',
 'WIND AND STARS\xa0',
 'WISH UPON A STAR\xa0',
 'WONDER STAR',
 'WONDER STAR\xa0',
 'ZIGGY STARDUST\xa0']

In [28]:
df.loc[df['Horse']=='SPICY STAR\xa0']

,C-Sr#,Date,Season,Centre,Venue ID,Class,Distance,Race No,Horse,Age,Jockey,Trainer,Wt,Dr,Sh,Result,LBW,Sr #,Rtg,Penalty,Time in S,Odds,RunNo.,Venue Name
2374,B2375,2008-11-22,BW08,BLR,3,IV,1200.0,33,SPICY STAR,3,SAMUEL FARGEAT,NEIL DARASHAH,60.0,1,A,1,0.00,2375,0,0,0,0,-1,BLR
3016,B3017,2009-01-02,BW08,BLR,3,III,1200.0,95,SPICY STAR,4,SAMUEL FARGEAT,NEIL DARASHAH,58.5,12,A,3,3.75,3017,0,0,0,0,0,BLR
3826,B3827,2009-02-20,BW08,BLR,3,III,1200.0,170,SPICY STAR,4,S A DESOUSA,NEIL DARASHAH,58.5,3,A,3,4.50,3827,0,0,0,0,-1,BLR
4808,B4809,2009-05-17,BS09,BLR,3,III,1200.0,16,SPICY STAR,4,D GNANESHWAR,NEIL DARASHAH,58.0,7,A,8,9.25,4809,0,0,0,0,-1,BLR
5152,B5153,2009-06-06,BS09,BLR,3,III,1200.0,49,SPICY STAR,4,SURAJ NARREDU,NEIL DARASHAH,60.0,2,A,7,11.75,5153,0,0,0,0,-1,BLR
6631,B6632,2009-08-06,BS09,BLR,3,III,1200.0,195,SPICY STAR,4,A VELU,NEIL DARASHAH,56.0,11,S,11,14.25,6632,0,0,0,0,-1,BLR
7070,B7071,2009-11-14,BW09,BLR,3,III,1200.0,26,SPICY STAR,4,P S CHOUHAN,NEIL DARASHAH,58.0,6,S,5,8.50,7071,0,0,0,0,-1,BLR
7395,B7396,2009-12-04,BW09,BLR,3,III,1200.0,57,SPICY STAR,4,D GNANESHWAR,NEIL DARASHAH,56.5,8,S,7,12.75,7396,0,0,0,0,-1,BLR
7789,B7790,2009-12-25,BW09,BLR,3,III,1200.0,96,SPICY STAR,4,GAURAV SAPRA,NEIL DARASHAH,54.0,11,S,9,9.25,7790,0,0,0,0,-1,BLR
8198,B8199,2010-01-16,BW09,BLR,3,III,1200.0,137,SPICY STAR,5,B SREEKANTH,NEIL DARASHAH,53.0,2,S,10,9.00,8199,0,0,0,0,-1,BLR
8888,B8889,2010-02-26,BW09,BLR,3,IV,1200.0,206,SPICY STAR,5,J H CHRISTOPHER,NEIL DARASHAH,62.5,11,S,2,5.25,8889,0,0,0,0,-1,BLR
13316,B13317,2011-02-03,BW10,BLR,3,IV,1200.0,176,SPICY STAR,6,S JOHN,J BABU RAO,61.5,11,A,1,0.00,13317,0,0,0,0,-1,BLR
16966,B16967,2011-11-18,BW11,BLR,3,II,1200.0,29,SPICY STAR,6,VINOD SHINDE,R V MANOHAR,50.0,5,S,8,18.25,16967,0,0,0,0,-1,BLR
165297,My1965,2008-09-18,MyR08,MYS,8,IV,1200.0,10,SPICY STAR,3,A VELU,NEIL DARASHAH,58.0,1,S,2,3.25,165298,0,0,0,0,-1,MYS
165618,My2286,2008-10-03,MyR08,MYS,8,3y,1200.0,14,SPICY STAR,3,A VELU,NEIL DARASHAH,56.0,12,S,6,8.00,165619,0,0,0,0,-1,MYS
168890,My5558,2009-09-18,MyR09,MYS,8,III,1200.0,12,SPICY STAR,4,D GNANESHWAR,NEIL DARASHAH,54.0,11,S,7,4.00,168891,0,0,0,0,0,MYS
169214,My5882,2009-10-01,MyR09,MYS,8,III 4y&o,1200.0,16,SPICY STAR,4,V R JAGADEESH,NEIL DARASHAH,53.0,2,S,2,1.00,169215,0,0,0,0,-1,MYS
178572,My15240,2011-10-26,MyR11,MYS,8,III 5y&o,1200.0,18,SPICY STAR,6,B SREEKANTH,R V MANOHAR,60.0,2,S,10,19.50,178573,0,0,0,0,-1,MYS
182825,My19493,2012-10-21,MyR12,MYS,8,III 5y&o,1200.0,18,SPICY STAR,7,NASSAR ALAM,S SANTOSH RAO,60.0,2,S,11,22.75,182826,0,0,0,0,-1,MYS
183073,My19741,2012-11-14,MyW12,MYS,8,III,1200.0,2,SPICY STAR,7,AFSAR KHAN,S SANTOSH RAO,59.0,1,S,8,9.50,183074,0,0,0,0,-1,MYS
183325,My19993,2012-12-05,MyW12,MYS,8,III,1200.0,5,SPICY STAR,7,AFSAR KHAN,S SANTOSH RAO,58.0,7,S,11,19.00,183326,0,0,0,0,-1,MYS
183527,My20195,2012-12-19,MyW12,MYS,8,III 4y&o,1200.0,7,SPICY STAR,7,AFSAR KHAN,S SANTOSH RAO,58.0,4,S,9,13.75,183528,0,0,0,0,-1,MYS